### ISSUE TITLE
[Bug]: iOS AppName

### ISSUE THREAD

**Issue by forYouDevelop** [fluttercommunity/plus_plugins#1283]
### Platform

iOS

### Plugin

package_info_plus

### Version

3.0.1

### Flutter SDK

3.3.5

### Steps to reproduce

I have this crash on start app on simulator iPhone 14 pro max iOS 16.0

<img width="597" alt="image" src="https://user-images.githubusercontent.com/66330062/197332719-f3633119-69c9-43ba-8751-e802f70b9762.png">

### Logs

```shell
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'String'
#0      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:15:32)
<asynchronous suspension>
#1      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:41:26)
<asynchronous suspension>
#2      _initPackageInfo (package:facemassage/main.dart:52:28)
<asynchronous suspension>
#3      main (package:facemassage/main.dart:38:16)
<asynchronous suspension>
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale ru-BY)
    • Flutter version 3.3.5 on channel stable at /Users/kirilltupikov/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (3 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kirilltupikov/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 14 Pro Max (mobile)  • AE1BA1C2-048A-4879-A15D-ADC3FBFC53D2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
What are the contents of your info.plist? Do you have more than one app name through localization or similar?

**Comment by kl3ug** [comment]
BundleName doesn't mutate, only bundleIdentifier changes through .xcconfig files
