### ISSUE TITLE
Share_plus: missing plugin exception on Chrome / OSX

### ISSUE THREAD

**Issue by vmorilla** [fluttercommunity/plus_plugins#135]
## System info

Issue occurs on: Web - chrome (Safari works fine)
Plugin name: share_plus
Plugin version: ^2.1.0-nullsafety.0
Flutter doctor output:

```
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.2.1 20D74 darwin-x64, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)
```

## Steps to Reproduce

1. Running a simplified version of the example included in share_plus:
```dart
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';

void main() {
  runApp(DemoApp());
}

class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Share Plugin Demo',
      home: Scaffold(body: Center(
        child: Builder(
          builder: (BuildContext context) {
            return ElevatedButton(
              child: const Text('Share'),
              onPressed: () => _onShare(context),
            );
          },
        ),
      )),
    );
  }

  void _onShare(BuildContext context) async {
    final RenderBox box = context.findRenderObject() as RenderBox;

    await Share.share("Sample text",
        subject: "Sample subject",
        sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size);
  }
}

```
2. On chrome, pressing the share button will throw an MissingPluginException (see below).
In debug mode, before throwing the exception, the editor pauses on the _complete() method of class Completer of ticker.dart
It works fine on safari and IOS platform.
```
Error: MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)
    at Object.throw_ [as throw] (http://localhost:50005/dart_sdk.js:5028:11)
    at MethodChannel._invokeMethod (http://localhost:50005/packages/flutter/src/services/system_channels.dart.lib.js:953:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50005/dart_sdk.js:37206:33
    at _RootZone.runUnary (http://localhost:50005/dart_sdk.js:37077:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50005/dart_sdk.js:32333:29)
    at handleValueCallback (http://localhost:50005/dart_sdk.js:32860:49)
    at Function._propagateToListeners (http://localhost:50005/dart_sdk.js:32898:17)
    at _Future.new.[_completeWithValue] (http://localhost:50005/dart_sdk.js:32746:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50005/dart_sdk.js:32767:35)
    at Object._microtaskLoop (http://localhost:50005/dart_sdk.js:37329:13)
    at _startMicrotaskLoop (http://localhost:50005/dart_sdk.js:37335:13)
    at http://localhost:50005/dart_sdk.js:33106:9
```

### flutter run
```
[+1729 ms] [CHROME]:2021-02-13 19:40:32.382 Google Chrome[36317:346555] Error loading
/Library/CoreMediaIO/Plug-Ins/DAL/XpressionPlugin.plugin/Contents/MacOS/XpressionPlugin:
dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/XpressionPlugin.plugin/Contents/MacOS/XpressionPlugin, 262): no suitable image found.  Did find:
[   +1 ms] [CHROME]:    /Library/CoreMediaIO/Plug-Ins/DAL/XpressionPlugin.plugin/Contents/MacOS/XpressionPlugin: code signature in
(/Library/CoreMediaIO/Plug-Ins/DAL/XpressionPlugin.plugin/Contents/MacOS/XpressionPlugin) not valid for use in process using Library Validation:
mapping process and mapped file (non-platform) have different Team IDs
[        ] [CHROME]:    /Library/CoreMediaIO/Plug-Ins/DAL/XpressionPlugin.plugin/Contents/MacOS/XpressionPlugin: stat() failed with errno=9
[ +133 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:50972/devtools/browser/4198c2b4-abc0-4088-9009-7743970a1904
[ +703 ms] DwdsInjector: Received request for entrypoint at http://localhost:50952/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata
[   +8 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:50952/main_module.bootstrap.js
[+1834 ms] DevHandler: Debug service listening on ws://127.0.0.1:50996/HuocnB783yc=/ws

[  +11 ms] Debug service listening on ws://127.0.0.1:50996/HuocnB783yc=/ws
[        ] 💪 Running with sound null safety 💪
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+8081 ms] Error: MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)
                        at Object.throw_ [as throw] (http://localhost:50952/dart_sdk.js:5028:11)
                        at MethodChannel._invokeMethod (http://localhost:50952/packages/flutter/src/services/system_channels.dart.lib.js:953:21)
                        at _invokeMethod.next (<anonymous>)
                        at http://localhost:50952/dart_sdk.js:37206:33
                        at _RootZone.runUnary (http://localhost:50952/dart_sdk.js:37077:59)
                        at _FutureListener.thenAwait.handleValue (http://localhost:50952/dart_sdk.js:32333:29)
                        at handleValueCallback (http://localhost:50952/dart_sdk.js:32860:49)
                        at Function._propagateToListeners (http://localhost:50952/dart_sdk.js:32898:17)
                        at _Future.new.[_completeWithValue] (http://localhost:50952/dart_sdk.js:32746:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:50952/dart_sdk.js:32767:35)
                        at Object._microtaskLoop (http://localhost:50952/dart_sdk.js:37329:13)
                        at _startMicrotaskLoop (http://localhost:50952/dart_sdk.js:37335:13)
                        at http://localhost:50952/dart_sdk.js:33106:9

```

### flutter analyze
```
No issues found
```

### flutter doctor -v
```

[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.2.1 20D74 darwin-x64, locale es-ES)
    • Flutter version 1.26.0-17.5.pre at /Users/vmorilla/devel/flutter
    • Framework revision 1fe38dcb5f (3 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vmorilla/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • iPad Pro (12.9-inch) (4th generation) (mobile) • 4E251522-485D-4822-AEAD-BEB993173C6D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 88.0.4324.150
    ! Error: IPad is not connected. Xcode will continue when IPad is connected. (code -13)

• No issues found!
```

**Comment by jpnurmi** [comment]
Looks like a problem in `url_launcher`. Probably https://github.com/flutter/flutter/issues/71725 which has been merged but not released.

**Comment by mhadaily** [comment]
Please try again, it seems it has been fixed, if so, please close this PR or let us know. thanks
