### ISSUE TITLE
[Bug]: lateinit property mresult has not been initialized

### ISSUE THREAD

**Issue by stevenosse** [fluttercommunity/plus_plugins#1374]
### Platform

Android 11

### Plugin

share_plus

### Version

6.3.0

### Flutter SDK

3.3.5

### Steps to reproduce

1. Share file
2. Press the cancel button
3. The app crashed with the exception: `lateinit property mresult has not been initialized`

### Code Sample

```dart
Share.shareXFiles([XFile(filePath)], text: 'Hey, found an issue with the package ^^ ');
```

### Logs

```shell
D/AndroidRuntime(15430): Shutting down VM
E/AndroidRuntime(15430): FATAL EXCEPTION: main
E/AndroidRuntime(15430): Process: com.stevenosse.share_sample, PID: 15430
E/AndroidRuntime(15430): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=17062003, result=0, data=null} to activity {com.stevenosse.share_sample/com.stevenosse.share_sample.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mresult has not been initialized
E/AndroidRuntime(15430): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5162)
E/AndroidRuntime(15430): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5203)
E/AndroidRuntime(15430): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(15430): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15430): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15430): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
E/AndroidRuntime(15430): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15430): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(15430): 	at android.app.ActivityThread.main(ActivityThread.java:8056)
E/AndroidRuntime(15430): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(15430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(15430): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mresult has not been initialized
E/AndroidRuntime(15430): 	at com.media.storage.media_storage.MethodCallHandlerImpl.getMresult(MethodCallHandlerImpl.kt:60)
E/AndroidRuntime(15430): 	at com.media.storage.media_storage.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.kt:291)
E/AndroidRuntime(15430): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime(15430): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime(15430): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
E/AndroidRuntime(15430): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime(15430): 	at android.app.Activity.dispatchActivityResult(Activity.java:8524)
E/AndroidRuntime(15430): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5155)
E/AndroidRuntime(15430): 	... 11 more
I/Process (15430): Sending signal. PID: 15430 SIG: 9
Lost connection to device.
Exited (sigterm)
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [version 10.0.22621.819], locale fr-FR)
    • Flutter version 3.3.5 on channel stable at C:\Users\<USER>\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (7 weeks ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\<USER>\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\<USER>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[√] Connected device (3 available)
    • M2007J3SG (mobile) • a4e9d97e • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 108.0.5359.94
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Are you sure that it is from share plus? We don't have variables named `mresult` anywhere in the package.

**Comment by stevenosse** [comment]
I am sincerely sorry for the inconvenience.
After a good night's sleep, I realize that I posted the issue on the wrong repo without realizing it.
I'll take the liberty of closing the thread.
