### ISSUE TITLE
[Bug]: Exception on specific SM A105F Samsung model

### ISSUE THREAD

**Issue by saifkandil** [fluttercommunity/plus_plugins#1404]
### Platform

Android

### Plugin

Sensor_plus

### Version

2.0.1

### Flutter SDK

3.3.9

### Steps to reproduce

1. I use it to read ```MagnetometerEvent``` but there's an exception on my specific device and the library can't catch it

### Code Sample

```dart
void _listen() {
    _streamSubscriptions.add(
      magnetometerEvents.listen(
        (MagnetometerEvent event) {
          final compassAngle = _getCompassAngle(
            event.x,
            event.y,
          );
          final compassAngleString = _getCompassAngleString(compassAngle);
          emit(QiblaCompassListenSuccess(
            compassAngle,
            '${(((2 * pi) - compassAngle) * kToDegree).round().toString()}° $compassAngleString',
          ));
        },
        onError: (e) {
          emit(const QiblaCompassListenFailure(
            0.0,
            '0° N',
          ));
        },
        cancelOnError: true,
      ),
    );
  }
```

### Logs

```shell
[ +339 ms] 
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following PlatformException was thrown while activating platform stream on channel
                    dev.fluttercommunity.plus/sensors/magnetometer:
                    PlatformException(error, <get-sensor>(...) must not be null, null, null)

                    When the exception was thrown, this was the stack:
                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
                    <asynchronous suspension>
                    #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637:9)
                    <asynchronous suspension>
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19044.2251], locale en-GB)
    • Flutter version 3.3.9 on channel stable at C:\src\flutter\flutter                          
    • Upstream repository https://github.com/flutter/flutter.git                                 
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900                     
    • Engine revision 8f2221fbef                                                                 
    • Dart version 2.18.5                                                                        
    • DevTools version 2.15.0                                                                    
                                                                                                 
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)                 
    • Android SDK at C:\Users\saifs\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio
    • Android Studio at C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • android-studio-dir = C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5080.210
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\saifs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM A105F (mobile) • R58M65K2NGK • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 108.0.5359.99

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It seems that this phone has no magnetometer sensor: https://eu.community.samsung.com/t5/mobile-apps-services/a10-has-no-compass/td-p/1238385

Good catch to modify the plugin to check if sensor is available before setting the event stream.

**Comment by saifkandil** [comment]
thanks for reaching out @vbuberen, can I work on it? or the community will get this done? I really hope to work on it my self

**Comment by vbuberen** [comment]
We welcome contributions, so if you want to, feel free to create a PR.

**Comment by saifkandil** [comment]
thank u very much @vbuberen, I will work on it asap

**Comment by saifkandil** [comment]
hey @vbuberen, note that it's not for Magnetometer only we must check for the other sensors also because after running *#0*# on my device it seems that this A10 model only have Accelerometer though

**Comment by saifkandil** [comment]
I have a question regarding this problem also, the code crashes in some file that is not part of the plugin's files 
```
package:flutter/src/services/platform_channel.dart:296:18
package:flutter/src/services/message_codecs.dart:653:7
package:flutter/src/services/platform_channel.dart:637:9
```
this is normal right? the only changes will be made to the plugin am I right?

**Comment by saifkandil** [comment]
code for checking if the corresponding sensor exists or not will be added to ```StreamHandlerImpl.kt``` and ```SensorsPlugin.kt```, is that right? because I'm not supposed to edit flutter services lib, can u help with that so I can move on @vbuberen

**Comment by saifkandil** [comment]
Do I have to work on ios implementation? I don't want to install any VMs because I have a bad history with them. @vbuberen 😃

**Comment by saifkandil** [comment]
can u check my PR, please? @vbuberen I need to know if that's the right place for adding the change.
