### ISSUE TITLE
[Bug]: android_intent_plus CATEGORY_APP_GALLERY not working

### ISSUE THREAD

**Issue by BoHellgren** [fluttercommunity/plus_plugins#1424]
### Platform

Android 12

### Plugin

android_intent_plus

### Version

3.1.5

### Flutter SDK

3.3.9

### Steps to reproduce

See below

### Code Sample

```dart
With the old Intent plugin (no longer maintained) the following code works:
  var intent = android_intent.Intent();
  intent.setAction(android_action.Action.ACTION_MAIN);
  intent.addCategory(android_category.Category.CATEGORY_APP_GALLERY);
  intent.startActivity().catchError((e) => print(e));
Migrating to android_intent_plus, I changed this to
  print('Show gallery');
  AndroidIntent intent = AndroidIntent(
    action: 'ACTION_MAIN',
    category: 'CATEGORY_APP_GALLERY'
  );
  await intent.launch();
But this does not work, I get the error messages below.
```

### Logs

```shell
I/flutter ( 5865): Show gallery
I/MethodCallHandlerImpl( 5865): Cannot resolve explicit intent, falling back to implicit
V/IntentSender( 5865): Sending intent Intent { act=ACTION_MAIN cat=[CATEGORY_APP_GALLERY] (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): Failed to handle method call
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=ACTION_MAIN cat=[CATEGORY_APP_GALLERY] (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2100)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.Activity.startActivityForResult(Activity.java:5473)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.Activity.startActivityForResult(Activity.java:5431)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.Activity.startActivity(Activity.java:5817)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.Activity.startActivity(Activity.java:5770)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:101)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5865): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 5865): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=ACTION_MAIN cat=[CATEGORY_APP_GALLERY] (has extras) }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=ACTION_MAIN cat=[CATEGORY_APP_GALLERY] (has extras) }
E/flutter ( 5865): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2100)
E/flutter ( 5865): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
E/flutter ( 5865): 	at android.app.Activity.startActivityForResult(Activity.java:5473)
E/flutter ( 5865): 	at android.app.Activity.startActivityForResult(Activity.java:5431)
E/flutter ( 5865): 	at android.app.Activity.startActivity(Activity.java:5817)
E/flutter ( 5865): 	at android.app.Activity.startActivity(Activity.java:5770)
E/flutter ( 5865): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/flutter ( 5865): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:101)
E/flutter ( 5865): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 5865): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 5865): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 5865): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5865): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 5865): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5865): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 5865): 	at android.os.Looper.loop(Looper.java:313)
E/flutter ( 5865): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/flutter ( 5865): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5865): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter ( 5865): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 5865): )
E/flutter ( 5865): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 5865): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter ( 5865): <asynchronous suspension>
E/flutter ( 5865): #2      AndroidIntent.launch (package:android_intent_plus/android_intent.dart:150:5)
E/flutter ( 5865): <asynchronous suspension>
E/flutter ( 5865): #3      _MyHomePageState.build.<anonymous closure> (package:dog_camera/main.dart:164:11)
E/flutter ( 5865): <asynchronous suspension>
E/flutter ( 5865):
```

### Flutter Doctor

```shell
C:\Users\Bosse>flutter doctor -v
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.819], locale sv-SE)
    • Flutter version 3.3.9 on channel stable at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (5 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Bosse\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33122.133
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (4 available)
    • SM G970F (mobile) • RF8M3164L6B • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

C:\Users\Bosse>
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by BoHellgren** [comment]
The following works:
`AndroidIntent intent = AndroidIntent(
                  action: 'android.intent.action.MAIN',
                  category: 'android.intent.category.APP_GALLERY'
 );
await intent.launch(); `

Please add this to the example and the README. It would have saved me hours.
So would some support from the author. But I suppose this plugin is no longer supported (no reaction after two weeks). Then it should not be listed as a plus plugin.
