### ISSUE TITLE
[android_alarm_manager_plus] Crashes when the android activity is closed

### ISSUE THREAD

**Issue by Andrew-Bekhiet** [fluttercommunity/plus_plugins#144]
I have an issue in my app where I use android_alarm_manager_plus in delivering daily local notifications, but I've noticed this issue that occurs when the app is terminated and the android activity the cleared from the recents, where the app crashes on firing the callback

## System info

Issue occurs on: Android
Plugin name: android_alarm_manager_plus
Plugin version: tested on ^0.7.0-nullsafety.0 and ^0.6.0
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.19042.804], locale ar-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] VS Code, 64-bit edition (version 1.53.2)
[✓] Connected device (3 available)

• No issues found!
```

## Steps to Reproduce

1. Create new flutter project
2. Add android_alarm_manager_plus and flutter_local_notifications
3. Copy the 'ic_launcher' or any icon to android/res/main/drawable
4. Add the AndroidManifest required code:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.example.testproject">
  <application android:label="testproject"
    android:icon="@mipmap/ic_launcher">
    <activity android:name=".MainActivity"
      android:launchMode="singleTop"
      android:theme="@style/LaunchTheme"
      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
      android:hardwareAccelerated="true"
      android:windowSoftInputMode="adjustResize">
      <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
      <meta-data android:name="io.flutter.embedding.android.NormalTheme"
        android:resource="@style/NormalTheme" />
      <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
      <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable"
        android:resource="@drawable/launch_background" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
    <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
    <meta-data android:name="flutterEmbedding"
      android:value="2" />
    <service android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmService"
      android:permission="android.permission.BIND_JOB_SERVICE"
      android:exported="false"/>
    <receiver android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmBroadcastReceiver"
      android:exported="false"/>
    <receiver android:name="dev.fluttercommunity.plus.androidalarmmanager.RebootBroadcastReceiver"
      android:enabled="false">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"></action>
      </intent-filter>
    </receiver>


  </application>
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
  <uses-permission android:name="android.permission.WAKE_LOCK"/>

</manifest>

```
5. Run the following code:
```
import 'package:android_alarm_manager_plus/android_alarm_manager_plus.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AndroidAlarmManager.initialize();

  await FlutterLocalNotificationsPlugin().initialize(
      InitializationSettings(
          android: AndroidInitializationSettings('ic_launcher')),
      onSelectNotification: (_) async => showNotification());
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text('Demo app')),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          await AndroidAlarmManager.oneShot(
            Duration(minutes: 1),
            5,
            showNotification,
            exact: true,
            rescheduleOnReboot: true,
            allowWhileIdle: true,
          );
        },
      ),
    );
  }
}

void showNotification() async {
  print('showing notification');
  await FlutterLocalNotificationsPlugin().show(
      0,
      'Notification test',
      'content',
      NotificationDetails(
        android: AndroidNotificationDetails(
            'channelID', 'channel name', 'description',
            icon: 'ic_launcher',
            autoCancel: false,
            visibility: NotificationVisibility.secret,
            showWhen: false),
      ),
      payload: 'test');
}

```
4. Click the Floating Action Button to schedule the alarm
5. Close the app
6. Expected Behaviour: the alarm fires normally and the notification appears
7. Actual behaviour: the app crashes

## Logs
I can't get flutter run -v output as the issue appears when the app is closed, however this is the adb logcat output from Android studio:

```
2021-02-16 18:52:17.290 11209-11209/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2021-02-16 18:52:17.293 11209-11209/? E/Zygote: accessInfo : 1
2021-02-16 18:52:17.306 11209-11209/? I/ple.testprojec: Late-enabling -Xcheck:jni
2021-02-16 18:52:17.349 11209-11209/? E/ple.testprojec: Unknown bits set in runtime_flags: 0x8000
2021-02-16 18:52:17.365 11209-11209/? D/ActivityThread: setConscryptValidator
2021-02-16 18:52:17.365 11209-11209/? D/ActivityThread: setConscryptValidator - put
2021-02-16 18:52:18.362 11209-11209/com.example.testproject I/FlutterBackgroundExecutor: Starting AlarmService...
2021-02-16 18:52:18.387 11209-11209/com.example.testproject D/AndroidRuntime: Shutting down VM
2021-02-16 18:52:18.394 11209-11209/com.example.testproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testproject, PID: 11209
    java.lang.RuntimeException: Unable to create service dev.fluttercommunity.plus.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4412)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
        at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:366)
        at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:104)
        at dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:155)
        at dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:124)
        at dev.fluttercommunity.plus.androidalarmmanager.AlarmService.onCreate(AlarmService.java:345)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4400)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 

```

Flutter analyze:
```
Analyzing testproject...                                                

   info - Unused import: 'package:integration_test/integration_test.dart' - integration_test\app_test.dart:10:8 - unused_import
  error - The function 'run' isn't defined - integration_test\app_test.dart:14:16 - undefined_function

2 issues found. (ran in 19.8s)
```

```
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.19042.804], locale ar-EG)
    • Flutter version 1.26.0-17.5.pre at D:\Flutter
    • Framework revision 1fe38dcb5f (6 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Andre\AppData\Local\Android\Sdk\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Andre\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Andre\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.53.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • SM A515F (mobile) • 192.168.1.4:34456 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge              • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!
```

### Firebase crashlytics: 
![firebase crashlytics output](https://user-images.githubusercontent.com/40571928/108096938-30b68d80-708a-11eb-86b5-390d22afbc22.png)
![App Screenshot](https://user-images.githubusercontent.com/40571928/108097144-6d828480-708a-11eb-80e7-562827878ef9.jpeg)

**Comment by Andrew-Bekhiet** [comment]
Any updates on this??

**Comment by Andrew-Bekhiet** [comment]
After some more research, turns out the problem is with the ```android:name``` attribute in AndroidManifest.xml as mentioned in transistorsoft/flutter_background_fetch#160
I changed it to "io.flutter.app.FlutterApplication" and it worked

**Comment by underfilho** [comment]
> After some more research, turns out the problem is with the `android:name` attribute in AndroidManifest.xml as mentioned in [transistorsoft/flutter_background_fetch#160](https://github.com/transistorsoft/flutter_background_fetch/issues/160) I changed it to "io.flutter.app.FlutterApplication" and it worked

That solution does not work on Android Embedding v2, the `android:name` needs to be different from that
