### ISSUE TITLE
[Bug]: Android ANR ShareSuccessManager.java line 21

### ISSUE THREAD

**Issue by hrajwade96** [fluttercommunity/plus_plugins#1458]
### Platform

Android 11, Android 12, etc.

### Plugin

share_plus

### Version

5.0.0

### Flutter SDK

3.3.10

### Steps to reproduce

ShareSuccessManager.kt :

<details><summary>Expand code</summary><p>

```
package dev.fluttercommunity.plus.share

import android.content.*
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.PluginRegistry.ActivityResultListener
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Handles the callback based status information about a successful or dismissed
 * share. Used to link multiple different callbacks together for easier use.
 */
internal class ShareSuccessManager(private val context: Context) : BroadcastReceiver(),
    ActivityResultListener {
    private var callback: MethodChannel.Result? = null
    private var isCalledBack: AtomicBoolean = AtomicBoolean(true)

    /**
     * Register listener. Must be called before any share sheet is opened.
     */
    fun register() {
        context.registerReceiver(this, IntentFilter(BROADCAST_CHANNEL))
    }

    /**
     * Deregister listener. Must be called before the base activity is invalidated.
     */
    fun discard() {
        context.unregisterReceiver(this)
    }

    /**
     * Set result callback that will wait for the share-sheet to close and get either
     * the componentname of the chosen option or an empty string on dismissal.
     */
    fun setCallback(callback: MethodChannel.Result): Boolean {
        return if (isCalledBack.compareAndSet(true, false)) {
            isCalledBack.set(false)
            this.callback = callback
            true
        } else {
            callback.error(
                "Share callback error",
                "prior share-sheet did not call back, did you await it? Maybe use non-result variant",
                null,
            )
            false
        }
    }

    /**
     * Must be called if `.startActivityForResult` is not available to avoid deadlocking.
     */
    fun unavailable() {
        returnResult("dev.fluttercommunity.plus/share/unavailable")
    }

    /**
     * Send the result to flutter by invoking the previously set callback.
     */
    private fun returnResult(result: String) {
        if (isCalledBack.compareAndSet(false, true) && callback != null) {
            callback!!.success(result)
            callback = null
        }
    }

    /**
     * Handler called after a share sheet was closed. Called regardless of success or
     * dismissal.
     */
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        return if (requestCode == ACTIVITY_CODE) {
            returnResult("")
            true
        } else {
            false
        }
    }

    /**
     * Handler called after a sharesheet was closed. Called only on success.
     */
    override fun onReceive(context: Context, intent: Intent) {
        returnResult(
            intent.getParcelableExtra<ComponentName>(Intent.EXTRA_CHOSEN_COMPONENT).toString()
        )
    }

    companion object {
        const val BROADCAST_CHANNEL = "dev.fluttercommunity.plus/share/success"
        const val ACTIVITY_CODE = 17062003
    }
}


```</p></details>



### Code Sample

```dart
import 'package:cross_file/cross_file.dart';
import 'package:share_plus/share_plus.dart';

class ContentShareWrapper {
  void shareLinkAlongText(String shareContent) {
    Share.share(shareContent);
  }

  void shareFiles({required List<String> paths, String subject = 'Share'}) {
    if (paths.isNotEmpty) {
      final files = <XFile>[];
      paths.map((e) => files.add(XFile(e))).toList();
      Share.shareXFiles(
        files,
        subject: subject,
      );
    }
  }
}
```

```
### Logs

```shell
main (native):tid=1 systid=14990 
#00 pc 0x7590c libc.so (syscall + 28)
#01 pc 0x1b067c libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 148)
#02 pc 0x674128 libart.so (art::GoToRunnable(art::Thread*) + 480)
#03 pc 0x673f04 libart.so (art::JniMethodEnd(unsigned int, art::Thread*) + 28)
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:568)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5628)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1658)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1612)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1600)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:678)
       at dev.fluttercommunity.plus.share.ShareSuccessManager.register(ShareSuccessManager.java:21)
       at dev.fluttercommunity.plus.share.SharePlusPlugin.onAttachedToEngine(SharePlusPlugin.java:18)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:357)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:263)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:243)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:163)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:154)
       at io.flutter.embedding.engine.FlutterEngineGroup.createEngine(FlutterEngineGroup.java:182)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:151)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:120)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:99)
       at com.tp.flutter_embed.EngineBinding.<init>(EngineBinding.java:37)
       at com.tp.TcpApplication.initiateEngines(TcpApplication.java:123)
       at com.tp.TcpApplication.onCreate(TcpApplication.java:56)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7294)
       at android.app.ActivityThread.access$1700(ActivityThread.java:299)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

### Flutter Doctor

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0 22A380 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /Users/hrishikeshrajwade/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hrishikeshrajwade/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/hrishikeshrajwade/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by hrajwade96** [comment]
@brianegan @jpnurmi @anttikissa @krispypen. Can you help to fix this?
