### ISSUE TITLE
[Bug]: single-subscription battery state stream on Linux

### ISSUE THREAD

**Issue by jpnurmi** [fluttercommunity/plus_plugins#1478]
### Platform

Linux

### Plugin

battery_plus

### Version

3.0.2

### Flutter SDK

3.7.0

### Steps to reproduce

1. listen to `Battery.onBatteryStateChanged` multiple times

### Code Sample

```dart
import 'package:flutter/widgets.dart';
import 'package:battery_plus/battery_plus.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final battery = Battery();

  final first = battery.onBatteryStateChanged.listen((_) {});
  await first.cancel();

  // Exception: Bad state: Stream has already been listened to.
  final second = battery.onBatteryStateChanged.listen((_) {});
  await second.cancel();
}
```

### Logs

```shell
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
Connecting to VM Service at ws://127.0.0.1:34631/Bg1CjoYSFkk=/ws
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
#3      _AsBroadcastStream.listen (dart:async/stream_impl.dart:738:31)
#4      main
package:battery_plus_example/main.dart:12
<asynchronous suspension>
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.0, on Ubuntu 22.10 5.19.0-29-generic, locale en_US.UTF-8)
    • Flutter version 3.7.0 on channel stable at /home/jpnurmi/.fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/jpnurmi/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/jpnurmi/Android/Sdk
    • Java binary at: /home/jpnurmi/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.2-1
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/jpnurmi/Android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.10 5.19.0-29-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by jpnurmi** [comment]
https://api.dart.dev/stable/2.19.0/dart-async/Stream-class.html

> A single-subscription stream allows only a single listener during the whole lifetime of the stream.
> ...
> Listening twice on a single-subscription stream is not allowed, even after the first subscription has been canceled.
