### ISSUE TITLE
[Bug]: "type 'Null' is not a subtype of type 'String'"

### ISSUE THREAD

**Issue by MuhmdHsn313** [fluttercommunity/plus_plugins#1627]
### Platform

Android 12

### Plugin

device_info_plus

### Version

8.1.0

### Flutter SDK

3.7.7

### Steps to reproduce

I have this code:
```dart
 DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
  BaseDeviceInfo deviceInfo;
  if (Platform.isIOS) {
    deviceInfo = await deviceInfoPlugin.iosInfo;
  } else {
    deviceInfo = await deviceInfoPlugin.androidInfo;
  }
```

When I run it in Android Emulator this bug occurred:
```
"type 'Null' is not a subtype of type 'String'"
``` 

StackTrack:
```

#0      AndroidDeviceInfo.fromMap (package:device_info_plus/src/model/android_device_info.dart:154:24)
#1      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:53:29)
<asynchronous suspension>
...
...
...
```

### Code Sample

```dart
DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
  BaseDeviceInfo deviceInfo;
  if (Platform.isIOS) {
    deviceInfo = await deviceInfoPlugin.iosInfo;
  } else {
    deviceInfo = await deviceInfoPlugin.androidInfo;
  }
```

### Logs

```shell
#0      AndroidDeviceInfo.fromMap (package:device_info_plus/src/model/android_device_info.dart:154:24)
#1      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:53:29)
<asynchronous suspension>
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
    • Flutter version 3.7.7 on channel stable at C:\src\flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = ssh://git@github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (7 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\muhammad.hasan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.76.1)
    • VS Code at C:\Users\muhammad.hasan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]     
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 111.0.5563.64
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 111.0.1661.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Would be good if you provide a reproducable sample. Can't reproduce this issue with the example app of the plugin.

**Comment by vbuberen** [comment]
Since the issue can't be reproduced with provided code snippet and no activity from the reporter, closing this one.
