### ISSUE TITLE
Tests of flutter_test package fails

### ISSUE THREAD

**Issue by AnghelAndrei28** [fluttercommunity/plus_plugins#172]
## System info

The issue occurs on: Android
Plugin name: package_info_plus
Plugin version: 0.6.4
Flutter doctor output:

```
[√] Flutter (Channel unknown, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.804], locale ro-RO)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (4 available)

• No issues found!
```

## Steps to Reproduce

In order to test my application, I use the flutter_test package. The only tests that fail are those which go through your plugin. My guess is that flutter_test is not compatible with your plugin.

1. Install flutter_test package
2. Make an app that displays the version of it
3. Create a test that checks the version of the app using flutter_test
4. Run the test on your app

I attach a screenshot of the exceptions that cause the tests to fail:
![Exceptions](https://user-images.githubusercontent.com/45268599/109567814-a1c85d00-7aee-11eb-9389-c94db7702d50.png)

## Logs

```
[  +90 ms] executing: [D:\Users\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 022b333a089afb81c471ec43d1f1f4f26305d876
[        ] executing: [D:\Users\Flutter/] git tag --points-at HEAD
[  +37 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.24.0-10.2.pre
[   +7 ms] executing: [D:\Users\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +12 ms] executing: [D:\Users\Flutter/] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +27 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] executing: D:\Android\android-sdk\platform-tools\adb.exe devices -l
[  +35 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +47 ms] Downloading Web SDK...
[ +738 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/07c1eed46b9d9b58df78566e9b8b2e42e80d3380/flutte
r-web-sdk-windows-x64.zip md5 hash: rwW39r8dlFZZRIG8W2XCLg==
[+6249 ms] Downloading Web SDK... (completed in 7,0s)
[+3145 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] Multiple devices found:
[  +16 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[   +1 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 88.0.4324.190
[   +1 ms] Edge (web)       • edge       • web-javascript • Microsoft Edge 88.0.705.81
[   +1 ms] [0]: Web Server (web-server)
[        ] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+2607 ms] q
[   +3 ms] "flutter run" took 47.458ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices
(package:flutter_tools/src/device.dart:306:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:294:37)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices
           (package:flutter_tools/src/runner/flutter_command.dart:1106:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:427:15)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1040:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:931:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #14     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #15     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #18     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +5 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
No issues found! (ran in 3.4s)
```

```
[√] Flutter (Channel unknown, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.804], locale
    ro-RO)
    • Flutter version 1.24.0-10.2.pre at D:\Users\Flutter
    • Framework revision 022b333a08 (3 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Android\android-sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

**Comment by miquelbeltran** [comment]
Hi @AnghelAndrei28 I believe that the issue is trying to use a plugin from a Flutter Widget test.

You should isolate dependencies to platform specific plugins when writing tests and not call into plugins from them, but rather to fakes or mocks. 

Or if you want to test something that uses a platform plugin, use Integration Tests (also known as e2e or Flutter Driver tests): https://flutter.dev/docs/testing/integration-tests

I will mark this issue as closed, as it is unrelated to the code in the plus packages.
