### ISSUE TITLE
[Bug]: Can not send multi image with text 

### ISSUE THREAD

**Issue by longnbp189** [fluttercommunity/plus_plugins#1720]
### Platform

Android 11

### Plugin

share_plus

### Version

6.3.2

### Flutter SDK

3.7.10

### Steps to reproduce

I want to share multi images with text to another app. But it don't work.
Please help me

### Code Sample

```dart
Future<void> _shareInfoEvent(
      bool isImage, OwnerEstateDetailHeaderInfo data) async {
    final directory = await getTemporaryDirectory();
    List<String> listShareImage = [];
    String text = '';
    final files = <XFile>[];

    if (isImage) {
      text = shareInfoEstate(widget.data);
      for (var element in widget.data.images) {
        final url = Uri.parse("$domain${element.downloadPath}");

        List<String> listName = element.downloadPath?.split('/') ?? [];
        String name = listName.last;
        final response = await http.get(url);
        var file = await File('${directory.path}/$name')
            .writeAsBytes(response.bodyBytes);
        listShareImage.add('${directory.path}/$name');
        var xfile = XFile(file.path, name: name);
        files.add(xfile);
      }
      await Share.shareXFiles(
        files,
        text: text,
      );
    } else {
      text = shareInfoEstate(widget.data);
      await Share.share(
        text,
      );
    }
  }
```

### Logs

```shell
[   +5 ms] Downloading Web SDK...
[ +805 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/ec975089acb540fc60752606a3d3ba809dd1528b/flutter-web-sdk-windows-x64.zip md5     
hash: pgO0dP+ORL6kALk5Vu7Vcw==
[+4931 ms] Downloading Web SDK... (completed in 5.7s)
[+2688 ms] Downloading CanvasKit...
[ +629 ms] Content https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/ztaLvbs5GPmlAwUosC7VVp7EQnNVknRpNuKdv7vmzaAC md5 hash:
CnqDL1/YjPVj//AGTugKsA==
[ +244 ms] Downloading CanvasKit... (completed in 872ms)
[ +205 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +17 ms] "flutter run" took 10,346ms.
[  +11 ms] Target file "lib\main.dart" not found.
[   +2 ms] 
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1611:9)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:494:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1381:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +283 ms] ensureAnalyticsSent: 265ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

### Flutter Doctor

```shell
PS C:\Users\Admin\fph_agency> flutter doctor -v
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.25346.1001], locale en-US)
    • Flutter version 3.7.10 on channel stable at C:\Users\Admin\fvm\versions\3.7.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (5 available)
    • 21081111RG (mobile)                • 192.168.0.32:35459 • android-arm64  • Android 13 (API 33)
    • Android SDK built for x86 (mobile) • emulator-5554      • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows            • windows-x64    • Microsoft Windows [Version 10.0.25346.1001]
    • Chrome (web)                       • chrome             • web-javascript • Google Chrome 112.0.5615.50
    • Edge (web)                         • edge               • web-javascript • Microsoft Edge 112.0.1722.58

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
In the report you specified that the issue is on Android 11, but in the provided logs output it is definitely an attempt to build a web targeting app. Please provide proper info about the issue you are having.
