### ISSUE TITLE
[Bug]: Unsafe use of network_manager in connectivity_plus on linux

### ISSUE THREAD

**Issue by dballard** [fluttercommunity/plus_plugins#1789]
### Platform

linux

### Plugin

connectivity_plus

### Version

latest git

### Flutter SDK

3.7.1

### Steps to reproduce

1.  ``` 
  try {
    connectivityStream = await Connectivity().onConnectivityChanged.listen((ConnectivityResult result) { .... } );
  
  } catch (e) { print("error: $e"); }
```
2. Run on linux machine with no network manager

3. uncatchable SocketException crashes program 

### Code Sample

```dart
try {
    connectivityStream = await Connectivity().onConnectivityChanged.listen((ConnectivityResult result) { .... }, onError: (Object error) {
        // can catch startup errors like on Linux where dbus is unavailable (like test server)
        print("Error listening to connectivity for network state: {$error}");
        return null;
      }, cancelOnError: true );
  
  } catch (e) { print("error: $e"); }
```

### Logs

```shell
The following SocketException was thrown running a test:

Connection failed (OS Error: No such file or directory, errno = 2), address =

/var/run/dbus/system_bus_socket, port = 0


When the exception was thrown, this was the stack:

#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:694:35)

#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:960:12)

#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1843:26)

#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)

#4      DBusClient._openSocket (package:dbus/src/dbus_client.dart:767:31)

#5      DBusClient._connect (package:dbus/src/dbus_client.dart:787:11)

#6      DBusClient.callMethod (package:dbus/src/dbus_client.dart:607:11)

#7      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:448:22)

#8      DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:624:28)

#9      DBusSignalStream._onListen (package:dbus/src/dbus_client.dart:131:15)

#14     DBusSignalStream.listen (package:dbus/src/dbus_client.dart:124:31)

#18     NetworkManagerClient.connect (package:cwtch/third_party/nm/src/network_manager_client.dart:325:48)

#19     ConnectivityPlusLinuxPlugin._startListenConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:53:20)

#24     FlwtchState.startConnectivityListener (package:cwtch/main.dart:144:71)

#25     FlwtchState.initState (package:cwtch/main.dart:133:5)
```

### Flutter Doctor

```shell
it's a docker container we use for building

https://hub.docker.com/r/openpriv/flutter-desktop


+ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):

[!] Flutter (Channel unknown, 3.7.1, on Ubuntu 20.04.5 LTS 5.15.0-41-generic, locale en_US.UTF-8)

    ! Flutter version 3.7.1 on channel unknown at /sdks/flutter

      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.

      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.

    ! Unknown upstream repository.

      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.

[!] Android toolchain - develop for Android devices

    ✗ Unable to locate Android SDK.

      Install Android Studio from: https://developer.android.com/studio/index.html

      On first launch it will assist you in installing the Android SDK components.

      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

      If the Android SDK has been installed to a custom location, please use

      `flutter config --android-sdk` to update to that location.


    ✗ No valid Android SDK platforms found in /opt/android-sdk-linux/platforms. Directory was empty.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)

    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop

[!] Android Studio (not installed)

[✓] Connected device (1 available)

[✓] HTTP Host Availability


! Doctor found issues in 4 categories.
```
```


### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by dballard** [comment]
So from what I can see, the problem is, even if I pass in `onError` as a handler to ` Connectivity().onConnectivityChanged.listen` , it gets skipped in one case.

in `conectivity_plus_linux.dart` on line 37 you assign `onListen: _startListenConnectivity` which triggers an `    await _client!.connect();` that isn't in the await-able flow of code so when it gets an exception it brings the whole program down cus there is no way to catch it

**Comment by dballard** [comment]
Looks like the problem is replicated in dbus in `dbus_client.dart` under your use of network manager (`nm`) on linux. 

dbus_client.dart: 114: `    _controller.onListen = _onListen;`

again, uncatchable exception coming from with in nm. And without access to `nm`'s dbus client I'm not sure you can test / catch this...

Adding

```
 try {
      await _root.client.getNameOwner(_root.name);
    } on SocketException catch (e) {
      print("***** nm connect/emit test threw exception: $e");
      return;
    }
```

in nm NetworkManagerClient::connect() is able to check/catch it and even that is a bit hacky, but it directly triggers `callMethod` which directly triggers `_connect`  which is otherwise getting triggerd on `onListen` where the exception is uncatchable.

Would be nice if `nm` or `dbus` packages offered a way to check if dbus was available rather than throwing uncatchable exceptions on `.listen`

**Comment by brutalzinn** [comment]
same issue at Ubuntu Ubuntu 22.04.2 LTS

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (5 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
