### ISSUE TITLE
[Bug]: Share to Facebook crashing

### ISSUE THREAD

**Issue by water-user** [fluttercommunity/plus_plugins#1839]
### Platform

Android 11

### Plugin

share_plus

### Version

4.5.3

### Flutter SDK

3.72

### Steps to reproduce

Share to Facebook app

When clicking on share to "News Feed" or "Your groups" it's crash

![image](https://github.com/fluttercommunity/plus_plugins/assets/95235346/c8afc8a9-537c-4fbf-b0da-39a495718d94)

### Code Sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: Center(
        child: ElevatedButton(
          child: Text('Share'),
          onPressed: () => share(),
        ),
      )),
    );
  }

  void share() {
    Share.share('Share test');
  }
}
```

### Logs

```shell
E/AndroidRuntime(19626): FATAL EXCEPTION: main
E/AndroidRuntime(19626): Process: android:ui, PID: 19626
E/AndroidRuntime(19626): java.lang.ClassCastException: com.android.internal.app.ChooserActivityForCts cannot be cast to com.android.internal.app.ChooserActivity
E/AndroidRuntime(19626): 	at com.android.internal.app.ChooserStackedAppDialogFragment.onClick(ChooserStackedAppDialogFragment.java:63)
E/AndroidRuntime(19626): 	at com.android.internal.app.ChooserTargetActionsDialogFragment$VH.lambda$bind$0$ChooserTargetActionsDialogFragment$VH(ChooserTargetActionsDialogFragment.java:152)
E/AndroidRuntime(19626): 	at com.android.internal.app.-$$Lambda$ChooserTargetActionsDialogFragment$VH$-qUOTPR4BqyhKM1rxJEUUUrO6eY.onClick(Unknown Source:4)
E/AndroidRuntime(19626): 	at android.view.View.performClick(View.java:7582)
E/AndroidRuntime(19626): 	at android.view.View.performClickInternal(View.java:7555)
E/AndroidRuntime(19626): 	at android.view.View.access$3600(View.java:844)
E/AndroidRuntime(19626): 	at android.view.View$PerformClick.run(View.java:28979)
E/AndroidRuntime(19626): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(19626): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19626): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(19626): 	at android.app.ActivityThread.main(ActivityThread.java:8093)
E/AndroidRuntime(19626): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19626): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:676)
E/AndroidRuntime(19626): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
V/LOSING_EVENTS(17481): updateFlutterObserve - false , (onStop)
V/LifeCycleAppForPush(17481): isAppShow false
V/LOSING_EVENTS(17481): updateFlutterObserve - false , (onActivityStopped)
V/PhoneWindow(17481): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@fc194f0, this = DecorView@26dba69[MainActivity]
V/LOSING_EVENTS(17481): updateFlutterObserve - false , (onDestroy)
V/LifeCycleAppForPush(17481): isAppShow false
V/LOSING_EVENTS(17481): updateFlutterObserve - false , (onActivityDestroyed)
D/GetSocialPlugin(17481): detached from engine
D/libMEOW (17481): meow delete tls: 0xb40000754e801440
D/libMEOW (17481): meow destruct slot_opengl: 0xb40000754e801440, meow: 0xb40000754e801440
D/libMEOW (17481): meow delete tls: 0xb4000075300d6740
D/libMEOW (17481): meow destruct slot_opengl: 0xb4000075300d6740, meow: 0xb4000075300d6740
W/Activity(17481): Slow Operation: Activity .../.MainActivity onDestroy took 1052ms
D/View    (17481): [Warning] assignParent to null: this = DecorView@26dba69[MainActivity]
I/InputTransport(17481): Destroy ARC handle: 0xb4000075b1e435e0
W/Looper  (17481): PerfMonitor longMsg : seq=1955 plan=14:55:23.904 late=0ms wall=1166ms running=82ms runnable=22ms binder=10ms h=android.app.ActivityThread$H w=159 procState=10
I/Choreographer(17481): Skipped 68 frames!  The application may be doing too much work on its main thread.
W/Looper  (17481): PerfMonitor doFrame : time=0ms vsyncFrame=2014221 latency=1145ms procState=10 historyMsgCount=3 (msgIndex=1 wall=1166ms seq=1955 running=82ms runnable=22ms binder=10ms h=android.app.ActivityThread$H w=159)
I/Process (17481): Sending signal. PID: 17481 SIG: 9
Lost connection to device.
```

### Flutter Doctor

```shell
[!] Flutter (Channel stable, 3.7.2, on macOS 13.2.1 22D68 darwin-arm64, locale en-IL)
    • Flutter version 3.7.2 on channel stable at /Users/my/Documents/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Caskroom/flutter/2.10.0/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/my/Documents/flutter. Consider adding /Users/my/Documents/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32fb2f948e (3 months ago), 2023-02-08 07:30:10 -0800
    • Engine revision f40b73f8a4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/my/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/my/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • 21081111RG (mobile)      • k7u8get8qcq8rs75          • android-arm64  • Android 11 (API 30)
    • my’s iPhone (mobile) • 00008110-000E4D113631801E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 113.0.5672.126
    ! Error: my’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone
      and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
The crash log has nothing about share_plus's classes and since it is related to sharing to Facebook which we don't really support there is nothing to handle.
