### ISSUE TITLE
[Bug]: No activity found to handle Intent on Android 14 beta

### ISSUE THREAD

**Issue by moldovanAndrei99** [fluttercommunity/plus_plugins#1914]
### Platform

Android 14

### Plugin

share_plus

### Version

7.0.2

### Flutter SDK

3.7.8

### Steps to reproduce

1. Try to share anything

### Code Sample

```dart
Future<void> onShare() async {
    Share.share(
      "Store link",
      subject: 'Store link',
    );
  }
```

### Logs

```shell
[        ] Performing hot reload... (completed in 415ms)
[        ] Reloaded 0 libraries in 421ms (compile: 46 ms, reload: 0 ms, reassemble: 170 ms).
[+3042 ms] E/MethodChannel#dev.fluttercommunity.plus/share(16847): Failed to handle method call
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CHOOSER (has extras) }
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.Activity.startActivityForResult(Activity.java:5589)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.Activity.startActivityForResult(Activity.java:5547)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.Activity.startActivity(Activity.java:6045)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.Activity.startActivity(Activity.java:6012)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at dev.fluttercommunity.plus.share.Share.startActivity(Share.kt:160)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at dev.fluttercommunity.plus.share.Share.share(Share.kt:81)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at dev.fluttercommunity.plus.share.MethodCallHandler.onMethodCall(MethodCallHandler.kt:26)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/MethodChannel#dev.fluttercommunity.plus/share(16847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[   +2 ms] E/flutter (16847): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.CHOOSER (has extras) }, null,
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CHOOSER (has extras) }
[        ] E/flutter (16847): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
[        ] E/flutter (16847): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
[        ] E/flutter (16847): 	at android.app.Activity.startActivityForResult(Activity.java:5589)
[        ] E/flutter (16847): 	at android.app.Activity.startActivityForResult(Activity.java:5547)
[        ] E/flutter (16847): 	at android.app.Activity.startActivity(Activity.java:6045)
[        ] E/flutter (16847): 	at android.app.Activity.startActivity(Activity.java:6012)
[        ] E/flutter (16847): 	at dev.fluttercommunity.plus.share.Share.startActivity(Share.kt:160)
[        ] E/flutter (16847): 	at dev.fluttercommunity.plus.share.Share.share(Share.kt:81)
[        ] E/flutter (16847): 	at dev.fluttercommunity.plus.share.MethodCallHandler.onMethodCall(MethodCallHandler.kt:26)
[        ] E/flutter (16847): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
[        ] E/flutter (16847): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] E/flutter (16847): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
[        ] E/flutter (16847): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/flutter (16847): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/flutter (16847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/flutter (16847): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/flutter (16847): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/flutter (16847): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
[        ] E/flutter (16847): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (16847): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/flutter (16847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[        ] E/flutter (16847): )
[        ] E/flutter (16847): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
[        ] E/flutter (16847): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
[        ] E/flutter (16847): <asynchronous suspension>
[        ] E/flutter (16847):
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.4 22F66 darwin-arm64, locale en-RO)
    • Flutter version 3.7.8 on channel stable at /Users/andrei/Documents/Development/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (3 months ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/andrei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[!] Android Studio
    • Android Studio at /Users/andrei/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Users/andrei/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • 29011FDH200FAY • android-arm64  • Android 14 (API 34)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 114.0.5735.106

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [ ] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by andrii-z** [comment]
It is android 14 beta bug
There are two ways to fix the issue.

First requires root:
`$ adb root`
`$ adb shell pm enable com.android.intentresolver/.ChooserActivity`

Second is factory reset

[Source](https://www.reddit.com/r/android_beta/comments/146v09p/image_sharing/jnu3bdk?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)

**Comment by vbuberen** [comment]
Thanks for finding the reason. Closing as not plugins issue.

**Comment by Kreuger** [comment]
> It is android 14 beta bug There are two ways to fix the issue.
> 
> First requires root: `$ adb root` `$ adb shell pm enable com.android.intentresolver/.ChooserActivity`
> 
> Second is factory reset
> 
> [Source](https://www.reddit.com/r/android_beta/comments/146v09p/image_sharing/jnu3bdk?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)

Is there **any** other way to accomplish this? Intentresolver is broken on my phone. I don't have root and I am trying to avoid having to do a factory reset.

**Comment by andrii-z** [comment]
> > It is android 14 beta bug There are two ways to fix the issue.
> > 
> > First requires root: `$ adb root` `$ adb shell pm enable com.android.intentresolver/.ChooserActivity`
> > 
> > Second is factory reset
> > 
> > [Source](https://www.reddit.com/r/android_beta/comments/146v09p/image_sharing/jnu3bdk?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)
> 
> Is there **any** other way to accomplish this? Intentresolver is broken on my phone. I don't have root and I am trying to avoid having to do a factory reset.

Update to stable Android 14 version

**Comment by Kreuger** [comment]
As far as I know, it is the stable update as it has been rolling out since before I got the device. There are no updates available. I just got the July 1st security patch a few days ago.
