### ISSUE TITLE
[Bug]: shareXFiles not working 

### ISSUE THREAD

**Issue by BrayanX44** [fluttercommunity/plus_plugins#1985]
### Platform

android 12

### Plugin

share_plus

### Version

7.0.2

### Flutter SDK

3.10.1

### Steps to reproduce

Get an existing file path
Using package implementation of shareXFiles

### Code Sample

```dart
Future<void> sharePDF2(String? name) async {
    var file = XFile('/storage/emulated/0/Download/image.png');
    var result = await share.Share.shareXFiles([file]);
    log(result.status.toString(), name: 'sharePDF2 share status');
  }
```

### Logs

```shell
[sharePDF2] start sharing
E/flutter ( 6060): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share failed, /storage/emulated/0/Download/image.png: The source file doesn't exist., null, null)
E/flutter ( 6060): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 6060): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 6060): <asynchronous suspension>
E/flutter ( 6060): #2      MethodChannelShare.shareFilesWithResult (package:share_plus_platform_interface/method_channel/method_channel_share.dart:134:9)
E/flutter ( 6060): <asynchronous suspension>
E/flutter ( 6060): #3      MyContributionsController.sharePDF2 (package:yap_client/src/features/app/presentation/controllers/my_contributions_controller.dart:147:18)
E/flutter ( 6060): <asynchronous suspension>
E/flutter ( 6060): #4      MyContributionsPage.openBottomSheet.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:yap_client/src/features/app/presentation/pages/my_contributions_page.dart:597:39)
E/flutter ( 6060): <asynchronous suspension>
E/flutter ( 6060):
```

### Flutter Doctor

```shell
allright here
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by liuchuancong** [comment]
The source file doesn't exist.  Look this!
