### ISSUE TITLE
namespace 'dev.fluttercommunity.plus.packageinfo

### ISSUE THREAD

**Issue by liqping** [fluttercommunity/plus_plugins#2020]
### What is your question?

Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method namespace() for arguments [dev.fluttercommunity.plus.packageinfo] on extension 'android' of type com.android.build.gradle.LibraryExtension.
	at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:184)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:86)

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by alexlovar** [comment]
upgrade your android\build.gradle android tool to 7 or newer:

dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
