### ISSUE TITLE
[Bug]: [device_info_plus]   Build.SERIAL causing crash on Android 6/7: NoClassDefFoundError: Failed resolution of: Lcom/yl/lib/privacy_proxy/ProxyProxyField;

### ISSUE THREAD

**Issue by akindone** [fluttercommunity/plus_plugins#2034]
### Platform

Android 6.0.1

### Plugin

device_info_plus

### Version

9.0.2

### Flutter SDK

3.10

### Steps to reproduce

using a android 6.0.1 device, using the example code, the app crashed. I checked the android FATAL EXCEPTION, and pasted it to below `Logs`. I found this line`  build["serialNumber"] =  Build.SERIAL` causing the exception. So I try-catch this line, and it is not crash
```
build["serialNumber"] = try {
    Build.SERIAL
} catch (e: Throwable) {
    Build.UNKNOWN
}
```

### Code Sample

```dart
the example of device_info_plus
```

### Logs

```shell
08-10 18:51:20.584  8322  8322 E AndroidRuntime: FATAL EXCEPTION: main
08-10 18:51:20.584  8322  8322 E AndroidRuntime: Process: tech.brainco.meditation_2c_flutter, PID: 8322
08-10 18:51:20.584  8322  8322 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yl/lib/privacy_proxy/ProxyProxyField;
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at dev.fluttercommunity.plus.device_info.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:89)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5628)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yl.lib.privacy_proxy.ProxyProxyField" on path: DexPathList[[zip file "/data/app/tech.brainco.meditation_2c_flutter-1/base.apk"],nativeLibraryDirectories=[/data/app/tech.brainco.meditation_2c_flutter-1/lib/arm64, /data/app/tech.brainco.meditation_2c_flutter-1/base.apk!/lib/arm64-v8a, /oem/lib64, /vendor/lib64, /system/lib64]]
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	... 12 more
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.yl.lib.privacy_proxy.ProxyProxyField
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 		... 13 more
08-10 18:51:20.584  8322  8322 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Flutter Doctor

```shell
[!] Flutter (Channel stable, 3.10.6, on macOS 13.0.1 22A400 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at /Users/jike/fvm/versions/3.10.6
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/jike/fvm/versions/3.10.6. Consider adding /Users/jike/fvm/versions/3.10.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/jike/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/jike/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
I don't have a device with Android 6, but can't reproduce the issue on emulator. From logs it seems not clear what exactly is wrong here.

Could you also specify where exactly you do the change with `try catch`?

**Comment by vbuberen** [comment]
No, I meant if you edited the code in your fork or where? 

Also, could you tell me on which devices you see the problem?

**Comment by akindone** [comment]
> No, I meant if you edited the code in your fork or where?
> 
> Also, could you tell me on which devices you see the problem?

I edited the code in my fork.  and one of the devices is a android 6.0.1
![image](https://github.com/fluttercommunity/plus_plugins/assets/17843738/8f129359-ecf9-480f-b62e-ad4bce413a6d)

**Comment by nohli** [comment]
Can you try

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    build["serialNumber"] = try {
        Build.getSerial()
    } catch (ex: SecurityException) {
        Build.UNKNOWN
    }
} else {
    build["serialNumber"] = Build.SERIAL
}
```
