### ISSUE TITLE
[device_info_plus][Bug]: Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by takapiroid88** [fluttercommunity/plus_plugins#2149]
### Platform

iOS16

### Plugin

device_info_plus

### Version

9.0.3

### Flutter SDK

3.13.2

### Steps to reproduce

play sample code from referring to README.

similar to #184

### Code Sample

```dart
final androidInfo = await DeviceInfoPlugin().androidInfo;
print(androidInfo);
```

### Logs

```shell
Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      AndroidBuildVersion._fromMap (package:device_info_plus/src/model/android_device_info.dart:241:20)
#1      AndroidDeviceInfo.fromMap (package:device_info_plus/src/model/android_device_info.dart:148:36)
#2      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:53:29)
```

### Flutter Doctor

```shell
[!] Flutter (Channel stable, 3.13.2, on macOS 12.6 21G115 darwin-arm64, locale ja-JP)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at xxxxxxxxxx. Consider adding xxxxxxxxxx to the front of your path.
    ! Upstream repository xxxxxxxxxx is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to xxxxxxxxxx to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Why do you try to get `androidInfo` on iOS? It is wrong usage of plugin's API, not a bug.
