### ISSUE TITLE
[android_intent_plus] No Activity found to handle Intent for `action_dial`

### ISSUE THREAD

**Issue by GroovinChip** [fluttercommunity/plus_plugins#230]
## System info

Issue occurs on: Android
Plugin name: android_intent_plus
Plugin version: 1.0.1
Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (5 available)

• No issues found!

```

## Steps to Reproduce

1. Clone https://github.com/GroovinChip/direct_dialer
2. Checkout the `android_intent_plus_migration` branch
3. Run the example app on an Android device or emulator, enter a phone number in the textfield, and press the DIAL button. Accept the "call" permission (and dial again if the call does not immediately try to start)

## Logs

```
V/IntentSender(21953): Sending intent Intent { act=action_dial dat=tel:xxxxxxxxxx (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): Failed to handle method call
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=action_dial dat=tel:xxxxxxxxxx (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2080)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.Activity.startActivityForResult(Activity.java:5377)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.Activity.startActivityForResult(Activity.java:5335)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.Activity.startActivity(Activity.java:5721)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.Activity.startActivity(Activity.java:5674)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:93)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(21953): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/flutter (21953): PlatformException(error, No Activity found to handle Intent { act=action_dial dat=tel:xxxxxxxxxx (has extras) }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=action_dial dat=tel:xxxxxxxxxx (has extras) }
I/flutter (21953): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2080)
I/flutter (21953): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
I/flutter (21953): 	at android.app.Activity.startActivityForResult(Activity.java:5377)
I/flutter (21953): 	at android.app.Activity.startActivityForResult(Activity.java:5335)
I/flutter (21953): 	at android.app.Activity.startActivity(Activity.java:5721)
I/flutter (21953): 	at android.app.Activity.startActivity(Activity.java:5674)
I/flutter (21953): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
I/flutter (21953): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:93)
I/flutter (21953): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (21953): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessa
```

```
No issues found! (ran in 7.9s)
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/groov/development/flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/groov/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM N986U1 (mobile)      • R5CN710PL4K                              • android-arm64  • Android 11 (API 30)
    • Reuvain’s iPad (mobile) • 3fdb2a519e4b48e371ac545eb110ae15dcfe451e • ios            • iOS 14.4.2
    • iPhone 12 (mobile)      • 1D59F6D1-A4EF-4EE4-A201-54A2DDDFCE18     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

```

**Comment by miquelbeltran** [comment]
Hi @GroovinChip ! 

I am not sure what is the plugin supposed to do if there's no activity that can handle that type of intent. Do you have a proposal or an alternative?

**Comment by GroovinChip** [comment]
The old `intent` package, which I'm looking to migrate from, seems to do this when starting the intent, I never had to set an activity myself. So it seemed like a bug to me that this plugin doesn't handle that.

**Comment by miquelbeltran** [comment]
Ok, I took a look at your code. So you are using the intent the `action_dial` and not `action_call`. I noticed that you are requesting permissions in your code, but that is not necessary for the `action_dial`, because it just opens the dialer, it does not start the call automatically. For that you need to use the `action_call` intent. 

Anyways, this is basically what you are doing right? 

```
final intent = AndroidIntent(
        action: 'action_dial',
        data: 'tel:$number',
);
intent.launch();
```

But I think that's not correct, you need to pass the constant value of the intent as seen here: https://developer.android.com/reference/android/content/Intent#ACTION_DIAL

so it should be  "android.intent.action.DIAL" instead

**Comment by GroovinChip** [comment]
Ah, that was leftover from an experiment. It really should be
`action_dial`. Does the solution of passing the full intent name hold true
regardless?

**Comment by GroovinChip** [comment]
Ah, that was leftover from an experiment. It really should be `action_dial`. Does the solution of passing the full intent name hold true regardless?

**Comment by miquelbeltran** [comment]
Yes, because `action_call` is the constant name, but you should pass the constant value so "android.intent.action.CALL"

**Comment by GroovinChip** [comment]
This does the job, thank you!
