### ISSUE TITLE
[share_plus] (Android) PlatformException ENOENT (No such file or directory) <- External copy of supplied file

### ISSUE THREAD

**Issue by Coronon** [fluttercommunity/plus_plugins#241]
## System info

Issue occurs on: Android
Plugin name: share_plus
Plugin version: 2.0.3 (tested 1.2.0 but exact same bug in codebase [checked])
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.985], locale en-NZ)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.56.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```
## Steps to Reproduce

Given: The device runs API Version 30 and does not have external storage

1. Try to share any file with Share.shareFiles

## Logs

```
[+68735 ms] I/flutter ( 9211): SHARING
[   +1 ms] I/flutter ( 9211): /data/user/0/de.rubinraithel.goapp/cache/GOApp-838838.png
[   +8 ms] W/ContextImpl( 9211): Failed to ensure /storage/emulated/0/Android/data/de.rubinraithel.goapp/cache: android.os.ServiceSpecificException:
(code -1)
[  +14 ms] W/ContextImpl( 9211): Failed to ensure /storage/emulated/0/Android/data/de.rubinraithel.goapp/cache: android.os.ServiceSpecificException: 
(code -1)
[   +6 ms] E/flutter ( 9211): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(share/GOApp-838838.png: open
failed: ENOENT (No such file or directory), null, null, null)
[   +1 ms] E/flutter ( 9211): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
[   +1 ms] E/flutter ( 9211): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
[        ] E/flutter ( 9211): <asynchronous suspension>
[        ] E/flutter ( 9211): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[   +1 ms] E/flutter ( 9211): #3      MethodChannelShare.shareFiles
(package:share_plus_platform_interface/method_channel/method_channel_share.dart:73:20)
[   +1 ms] E/flutter ( 9211): #4      Share.shareFiles (package:share_plus/share_plus.dart:95:22)
[        ] E/flutter ( 9211): #5      showDetailsDialog.<anonymous closure> (package:goapp/pages/vertretungsplan/details.dart:231:27)
[   +1 ms] E/flutter ( 9211): <asynchronous suspension>
[   +1 ms] E/flutter ( 9211): #6      showDetailsDialog.<anonymous closure> (package:goapp/pages/vertretungsplan/details.dart)
[        ] E/flutter ( 9211): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
[   +1 ms] E/flutter ( 9211): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
[   +1 ms] E/flutter ( 9211): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[   +1 ms] E/flutter ( 9211): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] E/flutter ( 9211): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] E/flutter ( 9211): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
[        ] E/flutter ( 9211): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
[   +1 ms] E/flutter ( 9211): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
[   +1 ms] E/flutter ( 9211): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[   +1 ms] E/flutter ( 9211): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] E/flutter ( 9211): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] E/flutter ( 9211): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] E/flutter ( 9211): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
[        ] E/flutter ( 9211): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[   +1 ms] E/flutter ( 9211): #21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] E/flutter ( 9211): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[   +1 ms] E/flutter ( 9211): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[   +3 ms] E/flutter ( 9211): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[   +2 ms] E/flutter ( 9211): #25     _rootRunUnary (dart:async/zone.dart:1206:13)
[   +3 ms] E/flutter ( 9211): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +2 ms] E/flutter ( 9211): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter ( 9211): #28     _invoke1 (dart:ui/hooks.dart:265:10)
[   +3 ms] E/flutter ( 9211): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[   +2 ms] E/flutter ( 9211):
```

```
Analyzing goapp...                                                      
No issues found! (ran in 8.1s)
```

```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.985], locale en-NZ)
    • Flutter version 1.22.3 at R:\Programme\Flutter
    • Framework revision 8874f21e79 (7 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at R:\Programme\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: R:\Programme\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at R:\Programme\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

## Resolution
In *share_plus/android/src/main/.../Share.java* -> `private File getExternalShareFolder` [should not use an external folder](https://developer.android.com/reference/android/content/Context#getExternalCacheDir()).
-> "Shared storage may not always be available, since removable media can be ejected by the user"

It is way more compatible if `getContext().getCacheDir()` is used here. This path should then be added to the *android/src/main/res/xml/flutter_share_file_paths.xml* as follows: `<cache-path name="cache" path="share/" />`. This would already fix the problem, it would be potentially smart to adjust the naming of certain methods though. **This fix works on my machine and resolves all problems** <- And it should work on yours too ;)

This works because we can guarantee the existence of this local app ChacheDir compared to any external media. Android began to [limit access to external media with API lvl 30](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()), but this plugin still uses `Environment.getExternalStorageDirectory()` to detect if a provided path is already external (ready for sharing) <- The returned path is simply invalid in most practical cases so it will never work.

**Comment by miquelbeltran** [comment]
Thanks @Coronon  do you know if this issue is also present in the original `share` package?

**Comment by Coronon** [comment]
Im not using nullsafety yet, and the most current version of share without ns doesnt work (pub error -> not found). But I will try to investigate

**Comment by Coronon** [comment]
If you like I would love to get involved and refactor the Android plugin a bit. There shouldnt be any breaking changes required. (I already have a few edits in my running versions)

**Comment by miquelbeltran** [comment]
yes! I'll be happy if you can submit your changes and I will test and review them.
