### ISSUE TITLE
[Bug]: device_info_plus violates Android StrictMode's IncorrectContextUseViolation

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [fluttercommunity/plus_plugins#2687]
### Platform

Android

### Plugin

device_info_plus

### Version

9.1.2

### Flutter SDK

3.19.3

### Steps to reproduce

Enable StrictMode checks for `IncorrectContextUseViolation` by adding to an application's `onCreate`, like so:

```
 public void onCreate() {
     StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
             .detectIncorrectContextUse()
             .penaltyLog()
             .penaltyDeath()
             .build());
     super.onCreate();
 }
 ```

Observe that the app fails due to StrictMode violation by device_info_plus.

### Logs

```shell
StrictMode policy violation:
			android.os.strictmode.IncorrectContextUseViolation: WindowManager should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
			at android.os.StrictMode.onIncorrectContextUsed(StrictMode.java:2260)
			at android.app.ContextImpl.getSystemService(ContextImpl.java:2116)
			at android.content.ContextWrapper.getSystemService(ContextWrapper.java:900)
			at dev.fluttercommunity.plus.device_info.DeviceInfoPlusPlugin.setupMethodChannel(DeviceInfoPlusPlugin.kt:26)
			at dev.fluttercommunity.plus.device_info.DeviceInfoPlusPlugin.onAttachedToEngine(DeviceInfoPlusPlugin.kt:16)
			at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147)
			at third_party.flutter_plugins.device_info_plus.android.DeviceInfoPlusPluginHiltRegistrant.registerWith(DeviceInfoPlusPluginHiltRegistrant.java:25)
			at com.google.android.apps.kids.familylink.flutter.plugins.testing.FakePluginRegistrar.registerWith(FakePluginRegistrar.java:130)
			at com.google.mobile.flutter.contrib.background.FlutterEngineConfigurationModule.lambda$provideFlutterEngineConfiguration$0(FlutterEngineConfigurationModule.java:40)
			at com.google.mobile.flutter.contrib.background.FlutterEngineConfigurationModule$$ExternalSyntheticLambda0.run(Unknown Source:4)
			at com.google.mobile.flutter.contrib.background.FlutterEngineConfiguration.warmUpEngineAndSetRoute(FlutterEngineConfiguration.java:193)
			at com.google.mobile.flutter.contrib.background.FlutterEngineConfiguration.startDartIsolateAndSetRoute(FlutterEngineConfiguration.java:253)
			at com.google.android.apps.kids.familylink.flutter.FlutterEngineManager.startDartIsolate(FlutterEngineManager.java:60)
			at com.google.android.apps.kids.familylink.flutter.standalone.StandaloneFlutterActivityInitializer.initialize(StandaloneFlutterActivityInitializer.java:32)
			at com.google.android.apps.kids.familylink.flutter.standalone.StandaloneFlutterActivity.onCreate(StandaloneFlutterActivity.java:55)
			at android.app.Activity.performCreate(Activity.java:8342)
			at android.app.Activity.performCreate(Activity.java:8321)
			at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
			at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:766)
			at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
			at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
			at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
			at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
			at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
			at android.os.Handler.dispatchMessage(Handler.java:106)
			at android.os.Looper.loopOnce(Looper.java:201)
```

### Flutter Doctor

```shell
[✓] Flutter (Channel google3, on Debian GNU/Linux rodete 6.5.13-1rodete2-amd64, locale
    en_US.UTF-8)
    • Framework revision c30f998eb5 (15 days ago), 2024-02-27T00:00:00.000
    • Engine revision 0bc21ea7bc
    • Dart version 67b2a25074

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /opt/android-studio-with-blaze-2022.3/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Debian GNU/Linux rodete 6.5.13-1rodete2-amd64

[✓] Google3 (on linux)
    • KVM enabled

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by ChristianEdwardPadilla** [comment]
This bug completely prevents Google Flutter apps from using device_info_plus.

The source of the issue is that this plugin should not be retrieving `WindowManager` from the application context (in [`DeviceInfoPlusPlugin.kt`](https://github.com/fluttercommunity/plus_plugins/blob/02aeed09f3796dd10ff36cc3f8a30bd137f187ae/packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.kt#L26)). It needs an `Activity`.

**Comment by miquelbeltran** [comment]
Actually I got a quick fix going
