### ISSUE TITLE
[Bug]: When sharing the second file, PlatformException for shareXFiles.

### ISSUE THREAD

**Issue by bemilyswom** [fluttercommunity/plus_plugins#2840]
### Platform

Android 11, 14

### Plugin

share_plus

### Version

8.0.3

### Flutter SDK

3.19.5

### Steps to reproduce

1. File sharing (shareXFiles)
2. Complete and confirm file sharing
3. Share the following files
4. Exception occurs and is not shared

The share and shareFiles methods are normal.

### Code Sample

```dart
if (shareFiles != null) {
        final xFiles = shareFiles.map((file) => XFile(file.path)).toList();
        await Share.shareXFiles(
          xFiles,
          sharePositionOrigin: sharePositionOrigin,
        );
      }
```

### Logs

```shell
I/flutter (16637): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16637): │ ⛔ :: Interceptor Zone Error : PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null), StackTrace : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter (16637): │ ⛔ #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (16637): │ ⛔ <asynchronous suspension>
I/flutter (16637): │ ⛔ #2      MethodChannelShare.shareFilesWithResult (package:share_plus_platform_interface/method_channel/method_channel_share.dart:151:9)
I/flutter (16637): │ ⛔ <asynchronous suspension>
I/flutter (16637): │ ⛔ #3      ShareInviteController.openShare (package:befamily_app/src/controllers/classes/share_invite_controller.dart:66:9)
I/flutter (16637): │ ⛔ <asynchronous suspension>
I/flutter (16637): │ ⛔ 
I/flutter (16637): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale ko-KR)
    • Flutter version 3.19.5 on channel stable at /Users/swom/Flutter/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3주 전), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/swom/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/swom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (3 available)
    • SM G973N (mobile) • R39M30SMMSF • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 14.0 23A344 darwin-arm64 (Rosetta)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 123.0.6312.122
    ! Error: Browsing on the local area network for bemily019의 iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Closing because this open PR addresses this: https://github.com/fluttercommunity/plus_plugins/pull/2832
