### ISSUE TITLE
[Bug]: await _networkInfo.getWifiName() return null. even i grant all the permission. 

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [fluttercommunity/plus_plugins#2844]
### Platform

Android 13 

### Plugin

network_info_plus

### Version

5.0.3

### Flutter SDK

3.16.1

### Steps to reproduce

run just  network_info_plus: ^5.0.3 plugin example 

![WhatsApp Image 2024-04-16 at 21 49 08](https://github.com/fluttercommunity/plus_plugins/assets/8521122/5490a77c-75c1-4269-851c-24953cdb1d8e)

<img width="1496" alt="Screenshot 2024-04-16 at 9 56 16 PM" src="https://github.com/fluttercommunity/plus_plugins/assets/8521122/02480eb4-5f2d-4960-b616-515838aa91ad">

### Logs

```shell
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x22
               A: android:compileSdkVersionCodename(0x01010573)="14" (Raw: "14")
               A: package="dev.fluttercommunity.plus.network_info_plus_example" (Raw:
               "dev.fluttercommunity.plus.network_info_plus_example")
               A: platformBuildVersionCode=(type 0x10)0x22
               A: platformBuildVersionName=(type 0x10)0xe
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x13
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x22
               E: uses-permission (line=11)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=12)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw:
                 "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=13)
                 A: android:name(0x01010003)="android.permission.ACCESS_FINE_LOCATION" (Raw:
                 "android.permission.ACCESS_FINE_LOCATION")
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.ACCESS_WIFI_STATE" (Raw:
                 "android.permission.ACCESS_WIFI_STATE")
               E: application (line=16)
                 A: android:label(0x01010001)="network_info_plus_example" (Raw: "network_info_plus_example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:extractNativeLibs(0x010104ea)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x01030009
                   A: android:name(0x01010003)="io.flutter.embedding.android.FlutterActivity" (Raw:
                   "io.flutter.embedding.android.FlutterActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:configChanges(0x0101001f)=(type 0x11)0x24b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=30)
                     E: action (line=31)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=33)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=37)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=41)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=44)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +1 ms] Stopping app 'app-debug.apk' on SM M426B.
[        ] executing: /Users/murtuzanalawala/Library/Android/sdk/platform-tools/adb -s RZCR404DE3X shell am force-stop
dev.fluttercommunity.plus.network_info_plus_example
[ +156 ms] executing: /Users/murtuzanalawala/Library/Android/sdk/platform-tools/adb -s RZCR404DE3X shell pm list packages
dev.fluttercommunity.plus.network_info_plus_example
[ +158 ms] 
                    Exception occurred while executing 'list':
                    java.lang.SecurityException: Shell does not have permission to access user 150
                     com.android.server.am.ActivityManagerService.handleIncomingUser:14999
                     android.app.ActivityManager.handleIncomingUser:4805
                     com.android.server.pm.PackageManagerShellCommand.translateUserId:3517
                        at com.android.server.am.UserController.handleIncomingUser(UserController.java:2680)
                        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14999)
                        at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4805)
                        at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3517)
                        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:969)
                        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:865)
                        at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:724)
                        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:226)
                        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
                        at android.os.ShellCommand.exec(ShellCommand.java:38)
                        at
                        com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7
                        071)
                        at android.os.Binder.shellCommand(Binder.java:1085)
                        at android.os.Binder.onTransact(Binder.java:903)
                        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)
                        at
                        com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7055)
                        at android.os.Binder.execTransactInternal(Binder.java:1321)
                        at android.os.Binder.execTransact(Binder.java:1280)
[  +19 ms] ProcessException: Process exited abnormally:

           Exception occurred while executing 'list':
           java.lang.SecurityException: Shell does not have permission to access user 150
            com.android.server.am.ActivityManagerService.handleIncomingUser:14999
            android.app.ActivityManager.handleIncomingUser:4805
            com.android.server.pm.PackageManagerShellCommand.translateUserId:3517
                at com.android.server.am.UserController.handleIncomingUser(UserController.java:2680)
                at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14999)
                at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4805)
                at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3517)
                at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:969)
                at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:865)
                at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:724)
                at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:226)
                at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
                at android.os.ShellCommand.exec(ShellCommand.java:38)
                at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7071)
                at android.os.Binder.shellCommand(Binder.java:1085)
                at android.os.Binder.onTransact(Binder.java:903)
                at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)
                at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7055)
                at android.os.Binder.execTransactInternal(Binder.java:1321)
                at android.os.Binder.execTransact(Binder.java:1280)
             Command: /Users/murtuzanalawala/Library/Android/sdk/platform-tools/adb -s RZCR404DE3X shell pm list packages
             dev.fluttercommunity.plus.network_info_plus_example
[   +5 ms] Installing APK.
[   +1 ms] Installing build/app/outputs/flutter-apk/app-debug.apk...
[        ] executing: /Users/murtuzanalawala/Library/Android/sdk/platform-tools/adb -s RZCR404DE3X install -t -r
/Users/murtuzanalawala/StudioProjects/plus_plugins/packages/network_info_plus/network_info_plus/example/build/app/outputs/flutte
r-apk/app-debug.apk
[+46540 ms] Performing Streamed Install
                     Success
[   +1 ms] Installing build/app/outputs/flutter-apk/app-debug.apk... (completed in 46.5s)
[   +4 ms] executing: /Users/murtuzanalawala/Library/Android/sdk/platform-tools/adb -s RZCR404DE3X shell echo -n
1ed87055da011b01b66c13be6ca1358727beae67 > /data/local/tmp/sky.dev.fluttercommunity.plus.network_info_plus_example.sha1
[ +134 ms] executing: /Users/murtuzanalawala/Library/Android/sdk/platform-tools/adb -s RZCR404DE3X shell -x logcat -v time -t 1
```

### Flutter Doctor

```shell
flutter doctor -v

[!] Flutter (Channel stable, 3.16.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-KW)
    • Flutter version 3.16.1 on channel stable at /Users/murtuzanalawala/Library/Android/fluttersdk/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.0/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/murtuzanalawala/Library/Android/fluttersdk/flutter. Consider adding
      /Users/murtuzanalawala/Library/Android/fluttersdk/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (5 months ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/murtuzanalawala/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • SM M426B (mobile) • RZCR404DE3X • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Have you tested on a physical device?

**Comment by NALAWALAMURTUZA** [comment]
@miquelbeltran yes

![WhatsApp Image 2024-04-17 at 10 10 24 AM](https://github.com/fluttercommunity/plus_plugins/assets/8521122/19208cab-b07d-40ca-aa93-a32b43bd315b)
![WhatsApp Image 2024-04-17 at 10 10 24 AM](https://github.com/fluttercommunity/plus_plugins/assets/8521122/49b22f56-fa11-4857-b603-ba6d420de94b)

**Comment by NALAWALAMURTUZA** [comment]
In screenshot itself shows. i attach **SM 42GB(Mobile)**

**Comment by miquelbeltran** [comment]
I mean... you aren't even connected to wifi??
