### ISSUE TITLE
cannot update to the latest version ^6.0.2 getting issue with easy_localization_loader library it depends on version ^5.0.1 , both the libraries are depened each other , please do something

### ISSUE THREAD

**Issue by Jassirlink** [fluttercommunity/plus_plugins#2846]
### Platform

all platforms

### Plugin

connectivity_plus

### Version

^6.0.2

### Flutter SDK

Sdk Version 3.19.5

### Steps to reproduce

when i try to update the latest  version of connectivity_plus library i am getting this issue 
Resolving dependencies... 
Because easy_localization_loader 2.0.1 depends on connectivity_plus ^5.0.1 and no versions of easy_localization_loader match >2.0.1 <3.0.0,
  easy_localization_loader ^2.0.1 requires connectivity_plus ^5.0.1.
So, because qualfon depends on both easy_localization_loader ^2.0.1 and connectivity_plus ^6.0.2, version solving failed.

this is the issue can it depends on easy_localization_loader library version 2.0.1 so can't update to latest version
please do something.
![connectivity_plus_bug_screenshot](https://github.com/fluttercommunity/plus_plugins/assets/24810795/a7b2edea-1205-4eca-8e99-a2d3eab39528)

### Logs

```shell
[ +139 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] executing: C:\Users\t0614\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +71 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +88 ms] Downloading Web SDK...
[ +549 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/flutter-web-sdk.zip md5 hash:
81WT3nJpBFVVJpB632hkpA==
[+11821 ms] Downloading Web SDK... (completed in 12.4s)
[ +732 ms] Downloading windows-x64-debug/windows-x64-flutter tools...
[ +789 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/windows-x64-debug/windows-x64-flutter.zip
md5 hash: SgKeZHXBgUoDhd9kzTdoSQ==
[+20962 ms] Downloading windows-x64-debug/windows-x64-flutter tools... (completed in 21.8s)
[+1084 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools...
[  +34 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/windows-x64/flutter-cpp-client-wrapper.zip
md5 hash: VHgWsNJuiAYAU/KzAlptfg==
[  +10 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools... (completed in 44ms)
[  +38 ms] Downloading windows-x64-profile/windows-x64-flutter tools...
[ +692 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/windows-x64-profile/windows-x64-flutter.zip
md5 hash: tYaLMK5n4MtElzMXjfuUSQ==
[+17955 ms] Downloading windows-x64-profile/windows-x64-flutter tools... (completed in 18.6s)
[ +937 ms] Downloading windows-x64-release/windows-x64-flutter tools...
[ +746 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/windows-x64-release/windows-x64-flutter.zip
md5 hash: dGAt75yMHOhrAWrn8ph5BA==
[+18743 ms] Downloading windows-x64-release/windows-x64-flutter tools... (completed in 19.5s)
[ +960 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] No supported devices connected.
[  +36 ms] 
           The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
           Chrome (web)      • chrome  • web-javascript • unknown
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.

[   +3 ms] "flutter run" took 76,445ms.
[  +54 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:592:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1704:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +266 ms] ensureAnalyticsSent: 264ms
[   +1 ms] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[ +151 ms] exiting with code 1
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3447], locale en-IN)
    • Flutter version 3.19.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\t0614\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33529.622
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[√] Android Studio (version 2021.3)
    • Android Studio at D:\AndroidStudioFiles
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)      • chrome  • web-javascript • unknown

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
This link can help you: https://dart.dev/tools/pub/dependencies check the section about `dependency_overrides`
