### ISSUE TITLE
[Bug]: Unable to get provider dev.fluttercommunity.plus.share.ShareFileProvider

### ISSUE THREAD

**Issue by Fudal** [fluttercommunity/plus_plugins#2855]
### Platform

Android 12

### Plugin

share_plus

### Version

9.0.0

### Flutter SDK

3.19.5

### Steps to reproduce

1. Upgrade share_plus version to 9.0.0
2. Try run the app on Android
3. See error "java.lang.RuntimeException: Unable to get provider dev.fluttercommunity.plus.share.ShareFileProvider: java.lang.ClassNotFoundException: Didn't find class "dev.fluttercommunity.plus.share.ShareFileProvider" on path: DexPathList[...]" and app doesn't run.

### Logs

```shell
Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
E/AndroidRuntime(27275): FATAL EXCEPTION: main
E/AndroidRuntime(27275): Process: app.name, PID: 27275
E/AndroidRuntime(27275): java.lang.RuntimeException: Unable to get provider dev.fluttercommunity.plus.share.ShareFileProvider: java.lang.ClassNotFoundException: Didn't find class "dev.fluttercommunity.plus.share.ShareFileProvider" on path: DexPathList[[zip file "/data/app/~~crLWH42WdZHWhDOFxSCDyg==/package.name-OYp3SeVdNQkPdvY_hDNQHA==/base.apk"],nativeLibraryDirectories=[/data/app/~~crLWH42WdZHWhDOFxSCDyg==/package.name-OYp3SeVdNQkPdvY_hDNQHA==/lib/arm64, /data/app/~~crLWH42WdZHWhDOFxSCDyg==/package.name-OYp3SeVdNQkPdvY_hDNQHA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
E/AndroidRuntime(27275): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8313)
E/AndroidRuntime(27275): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7810)
E/AndroidRuntime(27275): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7564)
E/AndroidRuntime(27275): 	at android.app.ActivityThread.access$1700(ActivityThread.java:315)
E/AndroidRuntime(27275): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
E/AndroidRuntime(27275): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27275): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(27275): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(27275): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(27275): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27275): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(27275): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Duplicated of https://github.com/fluttercommunity/plus_plugins/issues/2462#issuecomment-1977210437

Likely you need to update the gradle plugin in your project. You can find more information in that ticket.
