### ISSUE TITLE
Compilation failing for Web  deployment

### ISSUE THREAD

**Issue by abhisiroha** [fluttercommunity/plus_plugins#2857]
### Platform

Windows 11 

### Plugin

sensors_plus

### Version

5.0.1

### Flutter SDK

3.19.1

### Steps to reproduce

1. Add custom action with sensors plus and magnetometer utility.
2. Deploy on web 

### Code Sample

```dart
// Automatic FlutterFlow imports
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:math' as math;
import 'package:sensors_plus/sensors_plus.dart';

Future<double?> directionsDegress() async {
  // Subscribe to magnetometer events with the desired sampling rate
  final magnetometerStream = magnetometerEventStream();

  try {
    // Listen to the stream for magnetometer events
    final MagnetometerEvent event = await magnetometerStream.first;

    // Calculate direction in radians
    double directionRadians = math.atan2(event.y, event.x);

    // Convert radians to degrees
    double directionDegrees = directionRadians * (180 / math.pi);

    // Adjust angle to be relative to true north
    directionDegrees -= 90.0;
    if (directionDegrees < 0) {
      directionDegrees += 360.0; // Ensure angle is within the range [0, 360)
    }

    return directionDegrees;
  } catch (error) {
    // Handle error gracefully
    print('Error fetching magnetometer data: $error');
    return null;
  }
}
```

### Logs

```shell
Error: Command failed: flutter build web  --web-renderer canvaskit --no-pub --no-version-check 
Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
/opt/.pub-cache/hosted/pub.dev/sensors_plus-5.0.1/lib/src/web_sensors_interop.dart:76:20:
Internal Error: Unknown external method j:method(SensorOptions|constructor#)
  external factory SensorOptions({
                   ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.3.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Unknown external method j:method(SensorOptions|constructor#)
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:39:3)
#1      KernelSsaGraphBuilder._buildExternalFunctionNode (package:compiler/src/ssa/builder.dart:1825:5)
#2      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:439:15)
#3      DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:154:15)
#4      KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:427:21)
#5      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:525:22)
#6      CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#7      KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:507:18)
#8      SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:365:21)
#9      SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:99:28)
#10     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:409:30)
#11     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:331:43)
#12     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:466:29)
#13     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:752:70)
#14     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#15     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:752:32)
#16     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:750:28)
#18     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:154:15)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:748:18)
#20     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#21     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#22     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:744:16)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#24     Compiler.emptyQueue (package:compiler/src/compiler.dart:743:14)
#25     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:767:7)
#26     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#27     Compiler.processQueue (package:compiler/src/compiler.dart:761:14)
#28     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:472:5)
  Command: /sdks/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /sdks/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/sdks/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/04817c99c9fd4956f27505204f7e344335810aed/ --native-null-assertions --no-source-maps -O4 -o /tmp/ff_service_scratch/piddteA5sB2CuG94Uh1U/urbanflora/.dart_tool/flutter_build/57bccc2d6b32525fc9af464778390ad4/main.dart.js /tmp/ff_service_scratch/piddteA5sB2CuG94Uh1U/urbanflora/.dart_tool/flutter_build/57bccc2d6b32525fc9af464778390ad4/app.dill
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)

Error: Failed to compile application for the Web.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22631.3527], locale en-IN)
    • Flutter version 3.19.1 on channel stable at C:\Users\abhis\AppData\Roaming\FlutterFlow\flutterflow\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (9 weeks ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\abhis\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\abhis\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at C:\Users\abhis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3527]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.78
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.51

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [ ] All dependencies are up to date with `flutter pub upgrade`
- [ ] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Old version of dart, you need to upgrade your SDK.

See https://github.com/fluttercommunity/plus_plugins/issues/2812
