### ISSUE TITLE
I am getting 'No Activity found to handle Intent' error

### ISSUE THREAD

**Issue by joec05** [fluttercommunity/plus_plugins#3091]
### What is your question?

I have been trying to launch an intent with ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION, however the terminal showed this error.

```
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173): Failed to handle method call
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=com.pocket_music_player.music_player_app (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.Activity.startActivityForResult(Activity.java:5434)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.Activity.startActivityForResult(Activity.java:5364)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.Activity.startActivity(Activity.java:5778)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.Activity.startActivity(Activity.java:5731)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:101)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(Unknown Source:0)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.os.Looper.loop(Looper.java:255)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at android.app.ActivityThread.main(ActivityThread.java:8224)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 4173):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

And this is my code:

```
void _launchIntent() async {    
    final intent = AndroidIntent(
      action: 'android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION',
      arguments: <String, dynamic>{ },
      data: Uri.encodeFull("com.pocket_music_player.music_player_app")
    );
    intent.launch();
  }
```

These are my permissions in `AndroidManifest.xml`:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="33"/>
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
```

I have also tested out the other examples and they're working fine. Unfortunately I'm handling an entirely different action, so the examples aren't helping me much.

Can anyone point out my mistake? Thank you in advance.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
The error tells that no app in your phone is able to handle the requested intent.

See https://developer.android.com/reference/android/content/ActivityNotFoundException and https://developer.android.com/guide/components/intents-filters#ExampleSend to learn about implicit intents.

You probably want to remove the `data: Uri.encodeFull("com.pocket_music_player.music_player_app")` so it lets the OS present an app that can handle `android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION` (if any is available)

**Comment by joec05** [comment]
Thank you for the quick response. I tried removing `data: Uri.encodeFull("com.pocket_music_player.music_player_app")` and unfortunately the same error is still there. I have the `MANAGE_EXTERNAL_STORAGE` permission set up in my `AndroidManifest.xml`, so I'm not sure why is it still happening.

**Comment by miquelbeltran** [comment]
You should read what the intent is for here: https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION

The error you get already says why it doesn't work, because no activity in your device is able to handle it.

This has nothing to do with file permissions.
