### ISSUE TITLE
[Bug]: NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by kkaun** [fluttercommunity/plus_plugins#3146]
### Platform

Android 7, Android 14

### Plugin

share_plus

### Version

10.0.0

### Flutter SDK

3.22.3

### Steps to reproduce

1. Compose a list of files to share (in our case, only .pdf files support is required).
2. While app is running, ensure that share intent is launched, e.g. native plugin popup/snackbar with share options is appeared.
3. Without choosing any option, click outside of plugin share popup's focus area to dismiss it.
3.1. Optionally, pick any share provider option that can be cancelled (f.e., share via Bluetooth), and cancel it without fully finishing the share flow (f.e. by simple native back press).

Both p. 3 and 3.1 lead to Android exception provided in the "Logs" paragraph. It seems like provided exception cannot be handled on Flutter app side, and leads to the Flutter app crash by default.

### Code Sample

```
          final pdfFiles = <XFile>[];
          pdfFiles.add(XFile(path,
              mimeType: "application/pdf",
              name: "doc_${DateTime.now().millisecond}.pdf"));

          ShareResult shareResult = await Share.shareXFiles(pdfFiles,
              text: "TestText", subject: fileName);
         
          //in described cases, code never reaches further without additional android/MainActivity.kt modification:
          print("SHARE - status:" + shareResult.status.name); 
```

### Logs

```shell
E/AndroidRuntime(22539): FATAL EXCEPTION: main
E/AndroidRuntime(22539): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=22643, result=0, data=null} to activity {com.mycompany.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(22539): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
E/AndroidRuntime(22539): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
E/AndroidRuntime(22539): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime(22539): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
E/AndroidRuntime(22539): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(22539): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(22539): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/AndroidRuntime(22539): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22539): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale pt-PT)
    • Flutter version 3.22.3 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.92.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\VSCode
    • Flutter extension version 3.94.0

[√] Connected device (4 available)
    • I100HD (mobile)   • 0123456789A • android-arm    • Android 7.0 (API 24)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 127.0.2651.86

[√] Network resources
    • All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by kkaun** [comment]
Turns out, the reason was in another plugin's ActivityResult handler.
Closing the bug.
