### ISSUE TITLE
[Bug]: android SIGABRT

### ISSUE THREAD

**Issue by liamleeq** [fluttercommunity/plus_plugins#3343]
### Platform

Android 14  Android13  Android12

### Plugin

libflutter.so

### Version

3.22.2

### Flutter SDK

3.22.2

### Steps to reproduce

This is an online issue and we have not reproduced it locally.

### Logs

```shell
# Crashlytics - Stack trace
# Application: com.tinytaala.chat
# Platform: android
# Version: 2.10.1 (47)
# Issue: 77869d1c55be57e60aa42da8689bd19b
# Session: 6729E5CA024000012FA9876BDA1B2AFA_DNE_6_v2
# Date: Tue Nov 05 2024 17:35:12 GMT+0800 (新加坡标准时间)

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.tinytaala.chat/com.xsxy.voice.MainActivity}: java.lang.IllegalArgumentException: NetworkCallback was not registered
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5741)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5774)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Caused by java.lang.IllegalArgumentException: NetworkCallback was not registered
       at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:5498)
       at dev.fluttercommunity.plus.connectivity.ConnectivityBroadcastReceiver.onCancel(ConnectivityBroadcastReceiver.java:18)
       at dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.teardownChannels(ConnectivityPlugin.java:13)
       at dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.onDetachedFromEngine(ConnectivityPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(:122)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(:105)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(:18)
       at android.app.Activity.performDestroy(Activity.java:8665)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1438)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5728)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5774)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

FirebaseSessions_HandlerThread:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:339)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:351)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Flutter Doctor

```shell
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[v] Flutter (Channel stable, 3.22.2, on Microsoft Windows [HE # 10.0.22631.4317], Locale zh-CN)
• Flutter version 3.22.2 on channel stable at D: \FlutterSDK\flutter3.22.2
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 761747bfc5 (5 months ago), 2024-06-05 22:15:13 +0200
• Engine revision edd8546116
• Dart version 3.4.3
• DevTools version 2.34.3
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn
[v] Windows Version (Installed version of Windows is version 10
or higher)
[v]
Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at D: \Android\SDK
• Platform android-34, build-tools 34.0.0
• Java binary at: D:\Android \AndroidStudioNew\jbr\bin\java
• Java
version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
• All Android licenses accepted.
[v] Chrome - develop for the web
• Chrome at C: Program Files Google \Chrome \Application \chrome.exe
Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
• Visual Studio at D: (Software\MicrosoftVisualStudio2022Community
• Visual Studio Community 2022 version 17.11.35327.3
X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
MSVC v142 - VS 2019 C++ x64 x86 build tools
- If there are multiple build tool versions available, install the latest
C++ CHake tools for Windows
Windows 10 SDK
[V] Android Studio (version 2024.1)
• Android Studio at D: Android AndroidStudioNew
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
[v] Connected device
(3 available)
• Windows (desktop) • windows • windows-x64
• Microsoft Windows [R# 10.0.22631.4317]
• Chrome webo
• chrome
• web-javascript • Google Chrome 130.0.6723.92
• Edge (web)
• edge
• web-javascript • Microsoft Edge 130.0.2849.56
[vi Network resources
• All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by anies1212** [comment]
@liamleeq 
We encountered with the same problem too, when running e2e test on Firebase Test lab.
What did you do to fix this?
