### ISSUE TITLE
share plus plugin doesn't work on flutter web

### ISSUE THREAD

**Issue by kristijanMitrikk** [fluttercommunity/plus_plugins#357]

**Comment by ueman** [comment]
What exactly does not work?
Can you post a reproducible example?

**Comment by Zujaj** [comment]
```dart
 static Future<void> forTap(BuildContext context) async {
    context.findRenderObject()!.sendSemanticsEvent(const TapSemanticEvent());
    switch (_platform(context)) {
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return SystemSound.play(SystemSoundType.click);
      case TargetPlatform.iOS:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        return Future<void>.value();
    }
```

The error raises in C:\flutter\packages\flutter\lib\src\material\feedback.dart, in short the Feedback class .There seems to be no case defined for the web. Below is the debug console log:

```
Error: Unsupported operation: _Namespace
    at Object.throw_ [as throw] (http://localhost:54986/dart_sdk.js:5393:11)
    at Function.get _namespacePointer [as _namespacePointer] (http://localhost:54986/dart_sdk.js:57149:17)
    at Function._namespacePointer (http://localhost:54986/dart_sdk.js:54830:28)
    at Function._dispatchWithNamespace (http://localhost:54986/dart_sdk.js:54835:31)
    at io._File.new.open (http://localhost:54986/dart_sdk.js:54984:23)
    at io._File.new.writeAsBytes (http://localhost:54986/dart_sdk.js:55238:19)
    at capture (http://localhost:54986/packages/convert_widget_image_example/utils.dart.lib.js:39:17)
    at capture.next (<anonymous>)
    at http://localhost:54986/dart_sdk.js:40636:33
    at _RootZone.runUnary (http://localhost:54986/dart_sdk.js:40493:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54986/dart_sdk.js:35420:29)
    at handleValueCallback (http://localhost:54986/dart_sdk.js:36005:49)
    at Function._propagateToListeners (http://localhost:54986/dart_sdk.js:36043:17)
    at _Future.immediate.[_completeWithValue] (http://localhost:54986/dart_sdk.js:35885:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54986/dart_sdk.js:35908:35)
    at Object._microtaskLoop (http://localhost:54986/dart_sdk.js:40798:13)
    at _startMicrotaskLoop (http://localhost:54986/dart_sdk.js:40804:13)
    at http://localhost:54986/dart_sdk.js:36267:9

```

**Comment by ueman** [comment]
It kinda looks to me that you're trying to use dart:io's  `File` on web which will not work. Are you sure that's not the case?

**Comment by Zujaj** [comment]
Yup that's it, so will I be only able to share text?

**Comment by ueman** [comment]
Yes, at the moment that's the case.

**Comment by Zujaj** [comment]
> Yes, at the moment that's the case.

Any way to cover this issue?

**Comment by ueman** [comment]
Dart:io will never work on web.

But there's some progress here: https://github.com/fluttercommunity/plus_plugins/pull/318
