### ISSUE TITLE
[network_info_plus_windows]  FileSystemException: Cannot create link

### ISSUE THREAD

**Issue by YowFung** [fluttercommunity/plus_plugins#363]
I got the following error when I try to run my application on the Windows platform.
```txt
FileSystemException: Cannot create link, path = 'X:\proitav\projects\IPControl_App\src\app\visualm\windows\flutter\ephemeral\.plugin_symlinks\network_info_plus_windows' (OS Error: 函数不正确。, errno = 1)
```
<details>
<summary>flutter run -d windows -v</summary>

```log
[  +80 ms] executing: [C:\workspace\sdk\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +420 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] d79295af24c3ed621c33713ecda14ad196fd9c31
[   +1 ms] executing: [C:\workspace\sdk\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +45 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[   +1 ms] 2.2.2
[   +5 ms] executing: [C:\workspace\sdk\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [C:\workspace\sdk\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +126 ms] executing: [C:\workspace\sdk\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +104 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] executing: C:\Users\yowfung\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +17 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +74 ms] executing: C:\Users\yowfung\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +23 ms] Skipping pub get: version match.
[  +37 ms] Found plugin firebase_core at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_core-1.2.1\
[   +9 ms] Found plugin firebase_core_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_core_web-1.1.0\
[   +3 ms] Found plugin firebase_crashlytics at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_crashlytics-2.0.5\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_plugin_android_lifecycle-2.0.2\
[   +5 ms] Found plugin image_picker at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\image_picker-0.8.1+3\
[   +2 ms] Found plugin image_picker_for_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\image_picker_for_web-2.0.0\
[   +7 ms] Found plugin network_info_plus at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus-1.0.1\
[   +4 ms] Found plugin network_info_plus_linux at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_linux-1.0.1\
[   +4 ms] Found plugin network_info_plus_macos at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_macos-1.0.1\
[   +3 ms] Found plugin network_info_plus_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_web-1.0.1\
[   +1 ms] Found plugin network_info_plus_windows at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_windows-1.0.2\
[   +8 ms] Found plugin path_provider at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider-2.0.2\
[   +2 ms] Found plugin path_provider_linux at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider_windows-2.0.1\
[  +15 ms] Found plugin url_launcher at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher-6.0.9\
[   +2 ms] Found plugin url_launcher_linux at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_macos-2.0.0\
[   +3 ms] Found plugin url_launcher_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_web-2.0.1\
[   +2 ms] Found plugin url_launcher_windows at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_windows-2.0.0\
[  +19 ms] Found plugin common at X:\proitav\projects\IPControl_App\src\common\
[  +93 ms] Found plugin firebase_core at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_core-1.2.1\
[   +2 ms] Found plugin firebase_core_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_core_web-1.1.0\
[   +1 ms] Found plugin firebase_crashlytics at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\firebase_crashlytics-2.0.5\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_plugin_android_lifecycle-2.0.2\
[   +3 ms] Found plugin image_picker at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\image_picker-0.8.1+3\
[   +2 ms] Found plugin image_picker_for_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\image_picker_for_web-2.0.0\
[   +8 ms] Found plugin network_info_plus at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus-1.0.1\
[   +2 ms] Found plugin network_info_plus_linux at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_linux-1.0.1\
[   +2 ms] Found plugin network_info_plus_macos at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_macos-1.0.1\
[   +2 ms] Found plugin network_info_plus_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_web-1.0.1\
[   +2 ms] Found plugin network_info_plus_windows at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\network_info_plus_windows-1.0.2\
[   +3 ms] Found plugin path_provider at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider-2.0.2\
[   +1 ms] Found plugin path_provider_linux at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider_macos-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\path_provider_windows-2.0.1\
[   +7 ms] Found plugin url_launcher at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher-6.0.9\
[   +2 ms] Found plugin url_launcher_linux at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_web-2.0.1\
[   +2 ms] Found plugin url_launcher_windows at C:\Users\yowfung\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\url_launcher_windows-2.0.0\
[  +12 ms] Found plugin common at X:\proitav\projects\IPControl_App\src\common\
[  +15 ms] Generating X:\proitav\projects\IPControl_App\src\app\visualm\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +188 ms] Initializing file store
[  +16 ms] Skipping target: gen_localizations
[   +8 ms] complete
[   +8 ms] Launching lib\main.dart on Windows in debug mode...
[   +7 ms] C:\workspace\sdk\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\workspace\sdk\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\workspace\sdk\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\yowfung\AppData\Local\Temp\flutter_tools.73f636ff\flutter_tool.96bfcdcc\app.dill --packages X:\proitav\projects\IPControl_App\src\app\visualm\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +91 ms] <- compile package:visualm/main.dart
[  +79 ms] List of devices attached
[  +13 ms] List of devices attached
[+12043 ms] FileSystemException: Cannot create link, path = 'X:\proitav\projects\IPControl_App\src\app\visualm\windows\flutter\ephemeral\.plugin_symlinks\network_info_plus_windows' (OS Error: 函数不正确。
                     , errno = 1)
[  +11 ms] "flutter run" took 13,031ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

```
</details>

<details>
<summary>flutter doctor -v</summary>

```log
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.1052], locale zh-CN)
    • Flutter version 2.2.2 at C:\workspace\sdk\flutter
    • Framework revision d79295af24 (4 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\yowfung\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\yowfung\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1052]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.
```
</details>

**Comment by mhadaily** [comment]
this might be related to https://github.com/flutter/flutter/issues/80038 or https://github.com/flutter/flutter/issues/66224
