### ISSUE TITLE
[connectivity_plus] The Android app crashes for API < N

### ISSUE THREAD

**Issue by matpag** [fluttercommunity/plus_plugins#367]
With the latest `connectivity_plus: 1.0.5` the app crashes after being closed because it tries to unregister a receiver never registered (or already unregistered).

The problem is in this newly added `unregisterReceiver` call:
https://github.com/fluttercommunity/plus_plugins/blob/199a2c5e530b502d8e304853afb1c39338654e82/packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java#L70

We should wrap the call in a try-catch for max safety
```java
try {
   context.unregisterReceiver(this);
} catch (Exception e) { /* ignored */ } 
```

Crash stacktrace:
```
java.lang.RuntimeException: Unable to destroy activity {com.mypackage.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: dev.fluttercommunity.plus.connectivity.ConnectivityBroadcastReceiver@1903ad97
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
    at android.app.ActivityThread.access$1400(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
 Caused by: java.lang.IllegalArgumentException: Receiver not registered: dev.fluttercommunity.plus.connectivity.ConnectivityBroadcastReceiver@1903ad97
    at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:765)
    at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1666)
    at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:511)
    at dev.fluttercommunity.plus.connectivity.ConnectivityBroadcastReceiver.onCancel(ConnectivityBroadcastReceiver.java:70)
    at dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.teardownChannels(ConnectivityPlugin.java:58)
    at dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.onDetachedFromEngine(ConnectivityPlugin.java:36)
    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:262)
    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:278)
    at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:122)
    at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:434)
    at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:576)
    at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:693)
    at androidx.fragment.app.Fragment.performDetach(Fragment.java:2839)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
    at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
    at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
    at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
    at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
    at android.app.Activity.performDestroy(Activity.java:6169)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
 	... 10 more
```

Tested on Android emulator API 22, Flutter 2.0.5

**Comment by mhadaily** [comment]
PR #369 probably will solve it.
