### ISSUE TITLE
[android_intent_plus] melos run:e2e fails, running e2e test manually works

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#46]
## System info

Issue occurs on: Android
Plugin name: android_intent_plus
Plugin version: 0.4.0
Flutter doctor output:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

## Steps to Reproduce

1. Start Android emulator
2. Run `melos run:e2e`

The tests in `android_alarm_manager_plus` will pass, the test in `android_intent_plus` will fail.

However, **going to `android_intent_plus/example` and running the test manually works.** 

## Logs

The important issue is the `MissingPluginException` that happens when running the test from melos. Again, this does not happen when running the e2e test directly.

```
$ melos run test:e2e
   └> melos exec -c 1 --fail-fast --scope="*example*" --dir-exists=test_driver -- \  flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
       └> RUNNING

$ melos exec -c
   └> flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
       └> RUNNING (in 8 packages)

[android_alarm_manager_example]: Using device sdk gphone x86 arm.
[android_alarm_manager_example]: Starting application: ./test_driver/android_alarm_manager_plus_e2e.dart
[android_alarm_manager_example]: Running Gradle task 'assembleDebug'...                          
[android_alarm_manager_example]:     1.9s
[android_alarm_manager_example]: 
[android_alarm_manager_example]: ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[android_alarm_manager_example]: I/flutter ( 6145): Observatory listening on http://127.0.0.1:42225/UoZpXoV_Q_g=/
[android_alarm_manager_example]: VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:33439/gzHq9_siSak=/
[android_alarm_manager_example]: VMServiceFlutterDriver: Isolate found with number: 2105761743046391
[android_alarm_manager_example]: VMServiceFlutterDriver: Isolate is paused at start.
[android_alarm_manager_example]: VMServiceFlutterDriver: Attempting to resume isolate
[android_alarm_manager_example]: I/flutter ( 6145): 00:00 +0: oneshot cancelled before it fires
[android_alarm_manager_example]: I/FlutterBackgroundExecutor( 6145): Starting AlarmService...
[android_alarm_manager_example]: I/flutter ( 6145): readCounter
[android_alarm_manager_example]: VMServiceFlutterDriver: Connected to Flutter application.
[android_alarm_manager_example]: for isolates
[android_alarm_manager_example]: I/flutter ( 6145): read: 3
[android_alarm_manager_example]: I/flutter ( 6145): oneShot start
[android_alarm_manager_example]: I/flutter ( 6145): oneShot end
[android_alarm_manager_example]: I/flutter ( 6145): Canceling alarm...
[android_alarm_manager_example]: I/flutter ( 6145): Alarm canceled
[android_alarm_manager_example]: I/flutter ( 6145): readCounter
[android_alarm_manager_example]: I/flutter ( 6145): read: 3
[android_alarm_manager_example]: I/flutter ( 6145): Test end
[android_alarm_manager_example]: I/flutter ( 6145): 00:04 +1: oneshot cancelled after it fires
[android_alarm_manager_example]: I/flutter ( 6145): readCounter
[android_alarm_manager_example]: I/flutter ( 6145): read: 3
[android_alarm_manager_example]: I/flutter ( 6145): oneShot start
[android_alarm_manager_example]: I/flutter ( 6145): oneShot end

[ REMOVED LOG DATA]

[android_alarm_manager_example]: I/flutter ( 6145): readCounter
[android_alarm_manager_example]: I/flutter ( 6145): read: 6
[android_alarm_manager_example]: I/flutter ( 6145): 01:45 +3: (tearDownAll)
[android_alarm_manager_example]: I/flutter ( 6145): 01:45 +4: All tests passed!
[android_alarm_manager_example]: Stopping application instance.
[android_intent_example]: Using device sdk gphone x86 arm.
[android_intent_example]: Starting application: ./test_driver/android_intent_plus_e2e.dart
[android_intent_example]: Running Gradle task 'assembleDebug'...                          
[android_intent_example]:    14.0s
[android_intent_example]: ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[android_intent_example]: Installing build/app/outputs/flutter-apk/app.apk...             
[android_intent_example]:     0.4s
[android_intent_example]: I/flutter ( 6358): Observatory listening on http://127.0.0.1:37473/lAj8r9KhXkI=/
[android_intent_example]: VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:40057/4-R3HIsUFqg=/
[android_intent_example]: VMServiceFlutterDriver: Isolate found with number: 1667073683960387
[android_intent_example]: VMServiceFlutterDriver: Isolate is paused at start.
[android_intent_example]: VMServiceFlutterDriver: Attempting to resume isolate
[android_intent_example]: I/flutter ( 6358): 00:00 +0: Embedding example app loads
[android_intent_example]: I/flutter ( 6358): 00:00 +1: #launch throws when no Activity is found
[android_intent_example]: I/flutter ( 6358): (The following exception is now available via WidgetTester.takeException:)
[android_intent_example]: I/flutter ( 6358): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): The following TestFailure object was thrown running a test:
[android_intent_example]: I/flutter ( 6358):   Expected: throws satisfies function
[android_intent_example]: I/flutter ( 6358):   Actual: <Closure: () => Future<void>>
[android_intent_example]: I/flutter ( 6358):    Which: threw MissingPluginException:<MissingPluginException(No implementation found for method
[android_intent_example]: I/flutter ( 6358): launch on channel plugins.flutter.io/android_intent)>
[android_intent_example]: I/flutter ( 6358):           stack package:flutter/src/services/platform_channel.dart 157:7
[android_intent_example]: I/flutter ( 6358): MethodChannel._invokeMethod
[android_intent_example]: I/flutter ( 6358):                 ===== asynchronous gap ===========================
[android_intent_example]: I/flutter ( 6358):                 package:test_api
[android_intent_example]: I/flutter ( 6358): expectLater
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart 466:10
[android_intent_example]: I/flutter ( 6358): expectLater
[android_intent_example]: I/flutter ( 6358):                 home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
[android_intent_example]: I/flutter ( 6358): 46:11  main.<fn>
[android_intent_example]: I/flutter ( 6358):                 home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
[android_intent_example]: I/flutter ( 6358): 42:7   main.<fn>
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart 144:29
[android_intent_example]: I/flutter ( 6358): testWidgets.<fn>.<fn>
[android_intent_example]: I/flutter ( 6358):                 ===== asynchronous gap ===========================
[android_intent_example]: I/flutter ( 6358):                 dart:async
[android_intent_example]: I/flutter ( 6358): _asyncThenWrapperHelper
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart
[android_intent_example]: I/flutter ( 6358): testWidgets.<fn>.<fn>
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/binding.dart 794:19
[android_intent_example]: I/flutter ( 6358): TestWidgetsFlutterBinding._runTestBody
[android_intent_example]: I/flutter ( 6358):                 ===== asynchronous gap ===========================
[android_intent_example]: I/flutter ( 6358):                 dart:async
[android_intent_example]: I/flutter ( 6358): _CustomZone.runBinary
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/binding.dart 774:14
[android_intent_example]: I/flutter ( 6358): TestWidgetsFlutterBinding._runTest
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/binding.dart 1625:12
[android_intent_example]: I/flutter ( 6358): LiveTestWidgetsFlutterBinding.runTest
[android_intent_example]: I/flutter ( 6358):                 package:e2e/e2e.dart 100:17
[android_intent_example]: I/flutter ( 6358): E2EWidgetsFlutterBinding.runTest
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart 136:24
[android_intent_example]: I/flutter ( 6358): testWidgets.<fn>
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): When the exception was thrown, this was the stack:
[android_intent_example]: I/flutter ( 6358): #0      fail (package:test_api/src/frontend/expect.dart:155:31)
[android_intent_example]: I/flutter ( 6358): #1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:130:9)
[android_intent_example]: I/flutter ( 6358): #13     Throws._matchFuture (package:test_api/src/frontend/throws_matcher.dart)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #14     Throws.matchAsync (package:test_api/src/frontend/throws_matcher.dart:62:16)
[android_intent_example]: I/flutter ( 6358): #15     _expect (package:test_api/src/frontend/expect.dart:119:26)
[android_intent_example]: I/flutter ( 6358): #16     expectLater (package:test_api/src/frontend/expect.dart:75:5)
[android_intent_example]: I/flutter ( 6358): #17     expectLater (package:flutter_test/src/widget_tester.dart:466:10)
[android_intent_example]: I/flutter ( 6358): #18     main.<anonymous closure> (file:///home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart:46:11)
[android_intent_example]: I/flutter ( 6358): #19     main.<anonymous closure> (file:///home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart:42:7)
[android_intent_example]: I/flutter ( 6358): #20     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
[android_intent_example]: I/flutter ( 6358): (elided 29 frames from dart:async, dart:async-patch, and package:stack_trace)
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): The test description was:
[android_intent_example]: I/flutter ( 6358):   #launch throws when no Activity is found
[android_intent_example]: I/flutter ( 6358): ════════════════════════════════════════════════════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
[android_intent_example]: I/flutter ( 6358): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): The following TestFailure object was thrown running a test:
[android_intent_example]: I/flutter ( 6358):   Expected: throws satisfies function
[android_intent_example]: I/flutter ( 6358):   Actual: <Closure: () => Future<void>>
[android_intent_example]: I/flutter ( 6358):    Which: threw MissingPluginException:<MissingPluginException(No implementation found for method
[android_intent_example]: I/flutter ( 6358): launch on channel plugins.flutter.io/android_intent)>
[android_intent_example]: I/flutter ( 6358):           stack package:flutter/src/services/platform_channel.dart 157:7
[android_intent_example]: I/flutter ( 6358): MethodChannel._invokeMethod
[android_intent_example]: I/flutter ( 6358):                 ===== asynchronous gap ===========================
[android_intent_example]: I/flutter ( 6358):                 package:test_api
[android_intent_example]: I/flutter ( 6358): expectLater
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart 466:10
[android_intent_example]: I/flutter ( 6358): expectLater
[android_intent_example]: I/flutter ( 6358):                 home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
[android_intent_example]: I/flutter ( 6358): 46:11  main.<fn>
[android_intent_example]: I/flutter ( 6358):                 home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
[android_intent_example]: I/flutter ( 6358): 42:7   main.<fn>
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart 144:29
[android_intent_example]: I/flutter ( 6358): testWidgets.<fn>.<fn>
[android_intent_example]: I/flutter ( 6358):                 ===== asynchronous gap ===========================
[android_intent_example]: I/flutter ( 6358):                 dart:async
[android_intent_example]: I/flutter ( 6358): _asyncThenWrapperHelper
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart
[android_intent_example]: I/flutter ( 6358): testWidgets.<fn>.<fn>
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/binding.dart 794:19
[android_intent_example]: I/flutter ( 6358): TestWidgetsFlutterBinding._runTestBody
[android_intent_example]: I/flutter ( 6358):                 ===== asynchronous gap ===========================
[android_intent_example]: I/flutter ( 6358):                 dart:async
[android_intent_example]: I/flutter ( 6358): _CustomZone.runBinary
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/binding.dart 774:14
[android_intent_example]: I/flutter ( 6358): TestWidgetsFlutterBinding._runTest
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/binding.dart 1625:12
[android_intent_example]: I/flutter ( 6358): LiveTestWidgetsFlutterBinding.runTest
[android_intent_example]: I/flutter ( 6358):                 package:e2e/e2e.dart 100:17
[android_intent_example]: I/flutter ( 6358): E2EWidgetsFlutterBinding.runTest
[android_intent_example]: I/flutter ( 6358):                 package:flutter_test/src/widget_tester.dart 136:24
[android_intent_example]: I/flutter ( 6358): testWidgets.<fn>
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): When the exception was thrown, this was the stack:
[android_intent_example]: I/flutter ( 6358): #0      fail (package:test_api/src/frontend/expect.dart:155:31)
[android_intent_example]: I/flutter ( 6358): #1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:130:9)
[android_intent_example]: I/flutter ( 6358): #13     Throws._matchFuture (package:test_api/src/frontend/throws_matcher.dart)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #14     Throws.matchAsync (package:test_api/src/frontend/throws_matcher.dart:62:16)
[android_intent_example]: I/flutter ( 6358): #15     _expect (package:test_api/src/frontend/expect.dart:119:26)
[android_intent_example]: I/flutter ( 6358): #16     expectLater (package:test_api/src/frontend/expect.dart:75:5)
[android_intent_example]: I/flutter ( 6358): #17     expectLater (package:flutter_test/src/widget_tester.dart:466:10)
[android_intent_example]: I/flutter ( 6358): #18     main.<anonymous closure> (file:///home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart:46:11)
[android_intent_example]: I/flutter ( 6358): #19     main.<anonymous closure> (file:///home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart:42:7)
[android_intent_example]: I/flutter ( 6358): #20     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
[android_intent_example]: I/flutter ( 6358): (elided 29 frames from dart:async, dart:async-patch, and package:stack_trace)
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): The test description was:
[android_intent_example]: I/flutter ( 6358):   #launch throws when no Activity is found
[android_intent_example]: I/flutter ( 6358): ════════════════════════════════════════════════════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): 00:00 +1: #launch throws when no Activity is found [E]
[android_intent_example]: I/flutter ( 6358):   Test failed. See exception logs above.
[android_intent_example]: I/flutter ( 6358):   The test description was: #launch throws when no Activity is found
[android_intent_example]: I/flutter ( 6358):   
[android_intent_example]: I/flutter ( 6358): 00:00 +1 -1: #canResolveActivity returns true when example Activity is found
[android_intent_example]: I/flutter ( 6358): (The following exception is now available via WidgetTester.takeException:)
[android_intent_example]: I/flutter ( 6358): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): The following MissingPluginException was thrown running a test:
[android_intent_example]: I/flutter ( 6358): MissingPluginException(No implementation found for method canResolveActivity on channel
[android_intent_example]: I/flutter ( 6358): plugins.flutter.io/android_intent)
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): When the exception was thrown, this was the stack:
[android_intent_example]: I/flutter ( 6358): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[android_intent_example]: I/flutter ( 6358): #2      AndroidIntent.canResolveActivity (package:android_intent_plus/android_intent.dart:149:27)
[android_intent_example]: I/flutter ( 6358): #3      main.<anonymous closure> (file:///home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart:59:36)
[android_intent_example]: I/flutter ( 6358): #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
[android_intent_example]: I/flutter ( 6358): #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:794:19)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:774:14)
[android_intent_example]: I/flutter ( 6358): #10     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1625:12)
[android_intent_example]: I/flutter ( 6358): #11     E2EWidgetsFlutterBinding.runTest (package:e2e/e2e.dart:100:17)
[android_intent_example]: I/flutter ( 6358): #12     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:136:24)
[android_intent_example]: I/flutter ( 6358): #13     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
[android_intent_example]: I/flutter ( 6358): #19     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
[android_intent_example]: I/flutter ( 6358): #20     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
[android_intent_example]: I/flutter ( 6358): #25     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
[android_intent_example]: I/flutter ( 6358): #26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
[android_intent_example]: I/flutter ( 6358): #32     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
[android_intent_example]: I/flutter ( 6358): #33     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
[android_intent_example]: I/flutter ( 6358): #34     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
[android_intent_example]: I/flutter ( 6358): #41     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
[android_intent_example]: I/flutter ( 6358): #42     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
[android_intent_example]: I/flutter ( 6358): (elided 31 frames from dart:async and package:stack_trace)
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): The test description was:
[android_intent_example]: I/flutter ( 6358):   #canResolveActivity returns true when example Activity is found
[android_intent_example]: I/flutter ( 6358): ════════════════════════════════════════════════════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
[android_intent_example]: I/flutter ( 6358): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[android_intent_example]: I/flutter ( 6358): The following MissingPluginException was thrown running a test:
[android_intent_example]: I/flutter ( 6358): MissingPluginException(No implementation found for method canResolveActivity on channel
[android_intent_example]: I/flutter ( 6358): plugins.flutter.io/android_intent)
[android_intent_example]: I/flutter ( 6358): 
[android_intent_example]: I/flutter ( 6358): When the exception was thrown, this was the stack:
[android_intent_example]: I/flutter ( 6358): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[android_intent_example]: I/flutter ( 6358): #2      AndroidIntent.canResolveActivity (package:android_intent_plus/android_intent.dart:149:27)
[android_intent_example]: I/flutter ( 6358): #3      main.<anonymous closure> (file:///home/miquel/dev/projects/fluttercommunity/plus_plugins/packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart:59:36)
[android_intent_example]: I/flutter ( 6358): #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
[android_intent_example]: I/flutter ( 6358): #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:794:19)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:774:14)
[android_intent_example]: I/flutter ( 6358): #10     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1625:12)
[android_intent_example]: I/flutter ( 6358): #11     E2EWidgetsFlutterBinding.runTest (package:e2e/e2e.dart:100:17)
[android_intent_example]: I/flutter ( 6358): #12     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:136:24)
[android_intent_example]: I/flutter ( 6358): #13     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
[android_intent_example]: I/flutter ( 6358): <asynchronous suspension>
[android_intent_example]: I/flutter ( 6358): #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
[android_intent_example]: I/flutter ( 6358): #19     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
[android_intent_example]: I/flutter ( 6358): #20     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
[android_intent_example]: I/flutter ( 6358): #25     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
[android_intent_example]: I/flutter ( 6358): #26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
[android_intent_example]: I/flutter ( 6358): 00:00 +1 -1: #canResolveActivity returns true when example Activity is found [E]
[android_intent_example]: I/flutter ( 6358):   Test failed. See exception logs above.
[android_intent_example]: I/flutter ( 6358):   The test description was: #canResolveActivity returns true when example Activity is found
[android_intent_example]: I/flutter ( 6358):   
[android_intent_example]: I/flutter ( 6358): 00:00 +1 -2: #canResolveActivity returns false when no Activity is found
[android_intent_example]: I/flutter ( 6358): 00:00 +1 -2: #canResolveActivity returns false when no Activity is found [E]
[android_intent_example]: I/flutter ( 6358):   Test failed. See exception logs above.
[android_intent_example]: I/flutter ( 6358):   The test description was: #canResolveActivity returns false when no Activity is found
[android_intent_example]: I/flutter ( 6358):   
[android_intent_example]: I/flutter ( 6358): 00:00 +1 -3: (tearDownAll)
[android_intent_example]: I/flutter ( 6358): Warning: E2E test plugin was not detected.
[android_intent_example]: I/flutter ( 6358): 00:00 +2 -3: Some tests failed.
[android_intent_example]: VMServiceFlutterDriver: Connected to Flutter application.
[android_intent_example]: Stopping application instance.
[android_intent_example]: Driver tests failed: 1

$ melos exec -c
   └> flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
       └> FAILED (in 1 packages)
           └> android_intent_example (with exit code 1)

$ melos run test:e2e
   └> melos exec -c 1 --fail-fast --scope="*example*" --dir-exists=test_driver -- \  flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
       └> FAILED


```

**Comment by Elias8** [comment]
@miquelbeltran I believe the `melos run test:e2e` command is no longer valid (it is removed from the melos file). So could please confirm that and close the issue?

Thanks!
