### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: FLTPackageInfoPlugin'

### ISSUE THREAD

**Issue by stx** [fluttercommunity/plus_plugins#48]
## System info

Issue occurs on: iOS using physical device
Plugin name: package_info_plus
Plugin version: 0.5.0

## Steps to Reproduce

1. Replaced package_info with package_info_plus in existing project to use it on the web.

## Logs

```
[        ] Application launched on the device. Waiting for observatory port.
[+1680 ms] (lldb) 2020-11-14 10:42:07.904448-0700 Runner[542:51058] 6.33.0 - [Firebase/Core][I-COR000005] No app has
been configured yet.
[  +37 ms] [Firebase/Crashlytics] Version 4.6.2
[  +28 ms] Observatory URL on device: http://127.0.0.1:54268/
[   +8 ms] 6.33.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle
remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add
"FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
[        ] https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
[        ] to ensure proper integration.
[        ] *** Assertion failure in -[FlutterEngine registrarForPlugin:], FlutterEngine.mm:800
[        ] Attempting to forward device port 54268 to host port 59778
[        ] executing: /Users/james/Development/flutter/bin/cache/artifacts/usbmuxd/iproxy 59778:54268 --udid
1804847de2148c71fb62931b5c64fa533fa4cfe4
[        ] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate
plugin key: FLTPackageInfoPlugin'
[        ] *** First throw call stack:
[        ] (0x1aaf159d4 0x1be8c6b54 0x1aae244fc 0x1ac11c878 0x1066ac0f8 0x1046d7bd0 0x1046dccec 0x1046dcff4
0x1ad774c04 0x1ad776ba4 0x1ad77c28c 0x1ace52d48 0x1ad37b5ec 0x1ace53830 0x1ace53338 0x1ace5365c 0x1ace52f18
0x1ace5abc4 0x1ad294a2c 0x1ad392d14 0x1ace5a8b8 0x1acc99e84 0x1acc98924 0x1acc99ad0 0x1ad77a464 0x1ad2bb320
0x1b98ab7c4 0x1b98d31f0 0x1b98b8f20 0x1b98d2f04 0x1aab4e280 0x1aab27190 0x1b98f7f20 0x1b98f7be8 0x1b98f80bc
0x1aae95be0 0x1aae95ae0 0x1aae94e28 0x1aae8f3d0 0x1aae8eb90 0x1c11b1598 0x1ad778638 0x1ad77dbb8 0x1046dd1b8
0x1aab6d588)
[        ] libc++abi.dylib: terminating with uncaught exception of type NSException
[ +262 ms] Process 542 stopped
[        ] * thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
[        ]     frame #0: 0x00000001d605584c libsystem_kernel.dylib`__pthread_kill + 8
[        ] libsystem_kernel.dylib`__pthread_kill:
[        ] ->  0x1d605584c <+8>:  b.lo   0x1d6055868               ; <+36>
[        ]     0x1d6055850 <+12>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x1d6055854 <+16>: mov    x29, sp
[        ]     0x1d6055858 <+20>: bl     0x1d6032f5c               ; cerror_nocancel
[        ] Target 0: (Runner) stopped.
[        ] ios-deploy exited with code 0
[ +742 ms] Forwarded port ForwardedPort HOST:59778 to DEVICE:54268
[        ] Forwarded host port 59778 to device port 54268 for Observatory
[   +2 ms] Installing and launching... (completed in 35.6s)
[   +2 ms] Caching compiled dill
[  +53 ms] Connecting to service protocol: http://127.0.0.1:59778/
[   +1 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:59778/.
[  +66 ms] Fail to connect to service protocol: http://127.0.0.1:59778/: WebSocketChannelException:
WebSocketChannelException: HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:59778/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:59778/
[        ] "flutter run" took 92,526ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:608:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1075:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[  +45 ms] ensureAnalyticsSent: 42ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 2

```

```

[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-7.0.pre at /Users/james/Development/flutter
    • Framework revision a0860f6e87 (2 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Apollo (mobile)  • 1804847de2148c71fb62931b5c64fa533fa4cfe4 • ios            • iOS 14.2
    • macOS (desktop)  • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 86.0.4240.193

• No issues found!

```

**Comment by miquelbeltran** [comment]
Hi @stx, this should be fixed in the release 0.6.0 of https://pub.dev/packages/package_info_plus, as we have renamed the Method Channel and should avoid collisions with the original package_info.

**Comment by miquelbeltran** [comment]
Actually I am wrong, with the changes in 0.6.0 may not be enough and we need to rename the objc classes.

**Comment by miquelbeltran** [comment]
With the changes in 0.6.2 now it should be OK, I renamed the ObjC files on iOS so there's no collision with the package_info plugin, and tested it importing both packages on a project.
