### ISSUE TITLE
[android_alarm_manager_plus] cancel: broadcast receiver not found

### ISSUE THREAD

**Issue by TheCarpetMerchant** [fluttercommunity/plus_plugins#577]
Issue occurs on: Android
Plugin name: android_alarm_manager_plus
Plugin version: 2.0.2
Android SDK : 30

I am getting a message "cancel: broadcast receiver not found" when using `AndroidAlarmManager.cancel` after the alarm has gone off once.
What's more, my alarm set with `AndroidAlarmManager.periodic` runs only once. `AndroidAlarmManager.periodic` returns true.

I don't suppose this is normal, but I have no idea of how to fix it, it worked perfectly fine before and I don't know which change broke it. Ran `flutter pub cache clean` to no avail.

I made a new Flutter project and added this code :
```
import 'package:android_alarm_manager_plus/android_alarm_manager_plus.dart';

void printHello() {
  final DateTime now = DateTime.now();
  print("[$now] Hello, world!");
}

void main() async {
  // Be sure to add this line if initialize() call happens before runApp()
  WidgetsFlutterBinding.ensureInitialized();

  await AndroidAlarmManager.initialize();
  runApp(const MyApp());

  final int helloAlarmID = 0;
  await AndroidAlarmManager.periodic(const Duration(minutes: 1), helloAlarmID, printHello);
}
```

It doesn't work either (I waited for more then 10 minutes). I'm honestly at a loss as to what I'm supposed to do.
I'm considering downgrading Flutter to 2.2.3 since I don't remember having this issue before 2.5.

I'm also SOMETIMES getting this error, but it's very inconsistent (sometimes 1min after launch, sometimes 10). Having it or not doesn't change the result : the alarm is only fired once (without any problems whatsoever)
```
E/AndroidRuntime(12129): FATAL EXCEPTION: main
E/AndroidRuntime(12129): Process: com.dti.samsung, PID: 12129
E/AndroidRuntime(12129): java.lang.RuntimeException: Unable to create application com.digitalturbine.igniteui.AndroidApplicationInstance: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dti.samsung/com.digitalturbine.ignite.IgniteService }: app is in background uid UidRecord{430fb7e u0a247 TRNB idle change:idle|uncached procs:2 seq(0,0,0)}
E/AndroidRuntime(12129): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
E/AndroidRuntime(12129): 	at android.app.ActivityThread.access$1300(ActivityThread.java:270)
E/AndroidRuntime(12129): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2051)
E/AndroidRuntime(12129): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(12129): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(12129): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(12129): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12129): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12129): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(12129): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dti.samsung/com.digitalturbine.ignite.IgniteService }: app is in background uid UidRecord{430fb7e u0a247 TRNB idle change:idle|uncached procs:2 seq(0,0,0)}
E/AndroidRuntime(12129): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1687)
E/AndroidRuntime(12129): 	at android.app.ContextImpl.startService(ContextImpl.java:1632)
E/AndroidRuntime(12129): 	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnectorImpl.<init>(SourceFile:200)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnectorImpl.<init>(SourceFile:164)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnector.<init>(SourceFile:121)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnector.getInstance(SourceFile:80)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.controller.UIController.<init>(SourceFile:86)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.controller.UIController.init(SourceFile:112)
E/AndroidRuntime(12129): 	at com.digitalturbine.igniteui.AndroidApplicationInstance.onCreate(SourceFile:65)
E/AndroidRuntime(12129): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
E/AndroidRuntime(12129): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6993)
E/AndroidRuntime(12129): 	... 8 more
E/AndroidRuntime(12237): FATAL EXCEPTION: main
E/AndroidRuntime(12237): Process: com.dti.samsung, PID: 12237
E/AndroidRuntime(12237): java.lang.RuntimeException: Unable to create application com.digitalturbine.igniteui.AndroidApplicationInstance: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dti.samsung/com.digitalturbine.ignite.IgniteService }: app is in background uid UidRecord{e0e5065 u0a247 TRNB idle change:idle|uncached procs:2 seq(0,0,0)}
E/AndroidRuntime(12237): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
E/AndroidRuntime(12237): 	at android.app.ActivityThread.access$1300(ActivityThread.java:270)
E/AndroidRuntime(12237): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2051)
E/AndroidRuntime(12237): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(12237): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(12237): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(12237): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12237): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12237): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(12237): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dti.samsung/com.digitalturbine.ignite.IgniteService }: app is in background uid UidRecord{e0e5065 u0a247 TRNB idle change:idle|uncached procs:2 seq(0,0,0)}
E/AndroidRuntime(12237): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1687)
E/AndroidRuntime(12237): 	at android.app.ContextImpl.startService(ContextImpl.java:1632)
E/AndroidRuntime(12237): 	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnectorImpl.<init>(SourceFile:200)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnectorImpl.<init>(SourceFile:164)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnector.<init>(SourceFile:121)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnector.getInstance(SourceFile:80)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.controller.UIController.<init>(SourceFile:86)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.controller.UIController.init(SourceFile:112)
E/AndroidRuntime(12237): 	at com.digitalturbine.igniteui.AndroidApplicationInstance.onCreate(SourceFile:65)
E/AndroidRuntime(12237): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
E/AndroidRuntime(12237): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6993)
E/AndroidRuntime(12237): 	... 8 more
E/AndroidRuntime(12336): FATAL EXCEPTION: main
E/AndroidRuntime(12336): Process: com.dti.samsung, PID: 12336
E/AndroidRuntime(12336): java.lang.RuntimeException: Unable to create application com.digitalturbine.igniteui.AndroidApplicationInstance: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dti.samsung/com.digitalturbine.ignite.IgniteService }: app is in background uid UidRecord{3a10224 u0a247 TRNB idle change:idle|uncached procs:2 seq(0,0,0)}
E/AndroidRuntime(12336): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
E/AndroidRuntime(12336): 	at android.app.ActivityThread.access$1300(ActivityThread.java:270)
E/AndroidRuntime(12336): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2051)
E/AndroidRuntime(12336): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(12336): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(12336): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(12336): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12336): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(12336): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dti.samsung/com.digitalturbine.ignite.IgniteService }: app is in background uid UidRecord{3a10224 u0a247 TRNB idle change:idle|uncached procs:2 seq(0,0,0)}
E/AndroidRuntime(12336): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1687)
E/AndroidRuntime(12336): 	at android.app.ContextImpl.startService(ContextImpl.java:1632)
E/AndroidRuntime(12336): 	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnectorImpl.<init>(SourceFile:200)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnectorImpl.<init>(SourceFile:164)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnector.<init>(SourceFile:121)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.igniteconnector.IgniteConnector.getInstance(SourceFile:80)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.controller.UIController.<init>(SourceFile:86)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.controller.UIController.init(SourceFile:112)
E/AndroidRuntime(12336): 	at com.digitalturbine.igniteui.AndroidApplicationInstance.onCreate(SourceFile:65)
E/AndroidRuntime(12336): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
E/AndroidRuntime(12336): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6993)
E/AndroidRuntime(12336): 	... 8 more

```

flutter doctor -v
```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [version 10.0.19043.1288], locale fr-BE)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\jerom\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.59.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (3 available)
    • SM A750FN (mobile) • 32005e294fcf368d • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!
```

**Comment by harysdenym** [comment]
yes it happen to my application too, and also my periodic callback didnt fired.

**Comment by Aksoyhlc** [comment]
Any progress on this issue?

**Comment by TheCarpetMerchant** [comment]
I now use workmanager.
