### ISSUE TITLE
Cannot share text to whatsapp and instagram from flutter app 

### ISSUE THREAD

**Issue by fidelisakilan** [fluttercommunity/plus_plugins#613]
## System info

Issue occurs on: Android 
Plugin name: android_intent_plus
Plugin version: 3.0.2
Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] Connected device (2 available)
```

## Steps to Reproduce

1. Added android intent plus plugin to the project 
2. called AndroidIntent to share to whatsapp
3. failing and showing error in log

## Logs

```

```

```
I/IntentSender(12913): Cannot resolve explicit intent
V/IntentSender(12913): Sending intent Intent { act=android.intent.action.SEND dat=Use InStats to find your lost & secret followers 
V/IntentSender(12913): Get InStats for free : https://followeranalyzer.page.link/rniX typ=plain/text pkg=com.whatsapp (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): Failed to handle method call
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND dat=Use InStats to find your lost & secret followers 
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): Get InStats for free : https://followeranalyzer.page.link/rniX typ=plain/text pkg=com.whatsapp (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2073)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1733)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.Activity.startActivityForResult(Activity.java:5314)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.Activity.startActivityForResult(Activity.java:5272)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.Activity.startActivity(Activity.java:5658)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.Activity.startActivity(Activity.java:5611)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:93)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#dev.fluttercommunity.plus/android_intent(12913): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (12913): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.SEND dat=Use InStats to find your lost & secret followers 
E/flutter (12913): Get InStats for free : https://followeranalyzer.page.link/rniX typ=plain/text pkg=com.whatsapp (has extras) }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND dat=Use InStats to find your lost & secret followers 
E/flutter (12913): Get InStats for free : https://followeranalyzer.page.link/rniX typ=plain/text pkg=com.whatsapp (has extras) }
E/flutter (12913): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2073)
E/flutter (12913): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1733)
E/flutter (12913): 	at android.app.Activity.startActivityForResult(Activity.java:5314)
E/flutter (12913): 	at android.app.Activity.startActivityForResult(Activity.java:5272)
E/flutter (12913): 	at android.app.Activity.startActivity(Activity.java:5658)
E/flutter (12913): 	at android.app.Activity.startActivity(Activity.java:5611)
E/flutter (12913): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/flutter (12913): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:93)
E/flutter (12913): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (12913): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (12913): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (12913): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (12913): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (12913): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (12913): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/flutter (12913): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12913): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (12913): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (12913): )
E/flutter (12913): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (12913): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (12913): <asynchronous suspension>
E/flutter (12913): #2      AndroidIntent.launch (package:android_intent_plus/android_intent.dart:138:5)
E/flutter (12913): <asynchronous suspension>
E/flutter (12913): 
```

code snippet i used: 
```
 const intent = AndroidIntent(
                            action: 'android.intent.action.SEND',
                            type: 'plain/text',
                            data: INVITE_CONTENT,
                            package: 'com.whatsapp'
                          );
                          intent.launch();
```

**Comment by vbuberen** [comment]
The error says that there is no app with such package name. Are you sure that the device you use has Whatsapp installed?
Also, note that sharing won't work properly due to https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus#known-issues
