### ISSUE TITLE
[package_info_plus] Logs an exception at startup on android

### ISSUE THREAD

**Issue by insidewhy** [fluttercommunity/plus_plugins#628]
I get the following exception logged every time I call `await PackageInfo.fromPlatform()` and then I get no response.

```
E/flutter ( 3315): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No i
mplementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
E/flutter ( 3315): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7
)
E/flutter ( 3315): <asynchronous suspension>
E/flutter ( 3315): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356
:43)
E/flutter ( 3315): <asynchronous suspension>
E/flutter ( 3315): #2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_
channel_package_info.dart:13:17)
E/flutter ( 3315): <asynchronous suspension>
E/flutter ( 3315): #3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:67:26)
E/flutter ( 3315): <asynchronous suspension>
```

## System info

Issue occurs on: Android
Plugin name: package_info_plus
Plugin version: 1.3.0
Flutter doctor output: 

```
[✓] Flutter (Channel stable, 2.5.3, on Arch Linux 5.15.2-arch1-1, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/james/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 96.0.4664.45 Arch Linux

• No issues found!
```

**Comment by insidewhy** [comment]
It looks like the android code has not been built, I've done `flutter clean` followed by `flutter run` many times but it doesn't fix it.

**Comment by insidewhy** [comment]
Ah had to add `super.configureFlutterEngine(flutterEngine);` to my `configureFlutterEngine` call, the examples I found online didn't include this.
