### ISSUE TITLE
webBrowserInfo() has not been implemented

### ISSUE THREAD

**Issue by LauDijksterhuis** [fluttercommunity/plus_plugins#633]
Hi there,
I'm trying to get information from the browser my app is running in. However, when I tried, I got an error.
I thought I made a misstake in my code, so I tried the example from https://pub.dev/packages/device_info_plus/example .
But here I get the same error see below.

## System info

Issue occurs on: web
Plugin name: device_info_plus
Plugin version: ^3.1.1.
Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale nl-NL)
    • Flutter version 2.5.3 at /Users/laudijksterhuis/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/laudijksterhuis/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 74C1D939-3421-4308-BCBA-2AD942B62F54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome   
```

## Steps to Reproduce

Run the example in flutter 2.5.3 for web.

## Logs

```
Error: UnimplementedError: webBrowserInfo() has not been implemented.
    at Object.throw_ [as throw] (http://localhost:51237/dart_sdk.js:5061:11)
at method_channel_device_info.MethodChannelDeviceInfo.new.webBrowserInfo (http://localhost:51237/packages/device_info_plus_platform_interface/method_channel/method_channel_device_info.dart.lib.js:74:17)
at device_info_plus.DeviceInfoPlugin.new.webBrowserInfo (http://localhost:51237/packages/device_info_plus/device_info_plus.dart.lib.js:55:110)
    at webBrowserInfo.next (<anonymous>)
    at runBody (http://localhost:51237/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:51237/dart_sdk.js:38690:7)
at device_info_plus.DeviceInfoPlugin.new.get webBrowserInfo [as webBrowserInfo] (http://localhost:51237/packages/device_info_plus/device_info_plus.dart.lib.js:52:20)
at main._MyAppState.new.initPlatformState (http://localhost:51237/packages/test_web_app/main.dart.lib.js:290:92)
    at initPlatformState.next (<anonymous>)
    at runBody (http://localhost:51237/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:51237/dart_sdk.js:38690:7)
at main._MyAppState.new.initPlatformState (http://localhost:51237/packages/test_web_app/main.dart.lib.js:286:20)
at main._MyAppState.new.initState (http://localhost:51237/packages/test_web_app/main.dart.lib.js:283:12)
at framework.StatefulElement.new.[_firstBuild] (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:44730:54)
at framework.StatefulElement.new.mount (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23129:26)
at RenderObjectToWidgetElement.new.inflateWidget (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:21950:16)
at RenderObjectToWidgetElement.new.updateChild (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:21815:25)
at RenderObjectToWidgetElement.new.[_rebuild] (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46986:37)
at RenderObjectToWidgetElement.new.mount (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46966:29)
at http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46902:37
at framework.BuildOwner.new.buildScope (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:44221:13)
at RenderObjectToWidgetAdapter.new.attachToRenderTree (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46901:17)
at binding$5.WidgetsFlutterBinding.new.attachRootWidget (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46771:236)
at http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46765:14
    at internalCallback (http://localhost:51237/dart_sdk.js:25436:11)
Restarted application in 1.905ms.
Error: UnimplementedError: webBrowserInfo() has not been implemented.
    at Object.throw_ [as throw] (http://localhost:51237/dart_sdk.js:5061:11)
at method_channel_device_info.MethodChannelDeviceInfo.new.webBrowserInfo (http://localhost:51237/packages/device_info_plus_platform_interface/method_channel/method_channel_device_info.dart.lib.js:74:17)
at device_info_plus.DeviceInfoPlugin.new.webBrowserInfo (http://localhost:51237/packages/device_info_plus/device_info_plus.dart.lib.js:55:110)
    at webBrowserInfo.next (<anonymous>)
    at runBody (http://localhost:51237/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:51237/dart_sdk.js:38690:7)
at device_info_plus.DeviceInfoPlugin.new.get webBrowserInfo [as webBrowserInfo] (http://localhost:51237/packages/device_info_plus/device_info_plus.dart.lib.js:52:20)
at main._MyAppState.new.initPlatformState (http://localhost:51237/packages/test_web_app/main.dart.lib.js:290:92)
    at initPlatformState.next (<anonymous>)
    at runBody (http://localhost:51237/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:51237/dart_sdk.js:38690:7)
at main._MyAppState.new.initPlatformState (http://localhost:51237/packages/test_web_app/main.dart.lib.js:286:20)
at main._MyAppState.new.initState (http://localhost:51237/packages/test_web_app/main.dart.lib.js:283:12)
at framework.StatefulElement.new.[_firstBuild] (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:44730:54)
at framework.StatefulElement.new.mount (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23129:26)
at RenderObjectToWidgetElement.new.inflateWidget (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:21950:16)
at RenderObjectToWidgetElement.new.updateChild (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:21815:25)
at RenderObjectToWidgetElement.new.[_rebuild] (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46986:37)
at RenderObjectToWidgetElement.new.mount (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46966:29)
at http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46902:37
at framework.BuildOwner.new.buildScope (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:44221:13)
at RenderObjectToWidgetAdapter.new.attachToRenderTree (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46901:17)
at binding$5.WidgetsFlutterBinding.new.attachRootWidget (http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46771:236)
at http://localhost:51237/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46765:14
    at internalCallback (http://localhost:51237/dart_sdk.js:25436:11)
Error: UnimplementedError: webBrowserInfo() has not been implemented.
    at Object.throw_ [as throw] (http://localhost:51237/dart_sdk.js:5061:11)
at method_channel_device_info.MethodChannelDeviceInfo.new.webBrowserInfo (http://localhost:51237/packages/device_info_plus_platform_interface/method_channel/method_channel_device_info.dart.lib.js:74:17)
at device_info_plus.DeviceInfoPlugin.new.webBrowserInfo (http://localhost:51237/packages/device_info_plus/device_info_plus.dart.lib.js:55:110)
    at webBrowserInfo.next (<anonymous>)
    at runBody (http://localhost:51237/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:51237/dart_sdk.js:38690:7)
at device_info_plus.DeviceInfoPlugin.new.get webBrowserInfo [as webBrowserInfo] (http://localhost:51237/packages/device_info_plus/device_info_plus.dart.lib.js:52:20)

```

**Comment by Ibessas** [comment]
Any updates?
