### ISSUE TITLE
[device_info_plus] UnimplementedError when fetching info on Linux

### ISSUE THREAD

**Issue by cachapa** [fluttercommunity/plus_plugins#646]
I started getting the following exception after updating `device_info_plus` from `2.0.0` to `3.1.1`:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: UnimplementedError: linuxInfo() has not been implemented.
#0      DeviceInfoPlatform.linuxInfo (package:device_info_plus_platform_interface/device_info_plus_platform_interface.dart:69:5)
#1      DeviceInfoPlugin.linuxInfo (package:device_info_plus/device_info_plus.dart:58:50)
[…]
```

It seems to be a regression since downgrading to `2.0.0` works as expected.

## System info

Issue occurs on: Linux
Plugin name: device_info_plus
Plugin version: 3.1.1
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on Fedora Linux 35 (Workstation Edition)
    5.15.6-200.fc35.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by Poly-Pixel** [comment]
I am also getting this

**Comment by gutisalex** [comment]
I am also getting this on windows...
