### ISSUE TITLE
[device_info_plus] UnimplementedError: windowsInfo() has not been implemented.

### ISSUE THREAD

**Issue by sgsm74** [fluttercommunity/plus_plugins#668]
## System info

Issue occurs on: windows
Plugin name: package_info_plus
Plugin version: 3.2.0
Flutter doctor output:

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.196, on Microsoft Windows [Version 10.0.19044.1415], locale en-US)
    • Flutter version 2.9.0-1.0.pre.196 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b5f483bc8 (8 hours ago), 2021-12-25 19:54:08 -0500
    • Engine revision 726588e9b0
    • Dart version 2.16.0 (build 2.16.0-135.0.dev)
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.       
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Saeed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19044.1415]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 96.0.1054.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

## Steps to Reproduce

1. declare device info plugin using DeviceInfoPlugin
2. _readWindowsDeviceInfo(await deviceInfoPlugin.windowsInfo)

## Logs

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: UnimplementedError: windowsInfo() has not been implemented.
#0      DeviceInfoPlatform.windowsInfo
package:device_info_plus_platform_interface/device_info_plus_platform_interface.dart:87
#1      DeviceInfoPlugin.windowsInfo
package:device_info_plus/device_info_plus.dart:81
#2      initPlatformState
package:sefaresh/…/utils/extra_info.dart:25
#3      main.<anonymous closure>.<anonymous closure>
package:sefaresh/main.dart:57
#4      main.<anonymous closure>.<anonymous closure>
package:sefaresh/main.dart:54
#5      _rootRunBinary (dart:async/zone.dart:1450:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#7      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1832:18)
#8      _Zone._processUncaughtError (dart:async/zone.dart:1109:14)
#9      _CustomZone.handleUncaughtError (dart:async/zone.dart:1312:5)
#10     Future._propagateToListeners (dart:async/future_impl.dart:680:16)

```

**Comment by ChivialK** [comment]
Same error also happening on macOS: 
Plugin version: 3.2.1

MacOS -> Run flutter on Chrome(web)

```dart
final device = DeviceInfoPlugin();
await device.macOsInfo;
```
Error: UnimplementedError: macosInfo() has not been implemented.

**Comment by narumishi** [comment]
Any fix available? wondering the reason why windows plugin not performed correctly.

I have to import `device_info_plus_windows` manually and directly call `device_info_windows.DeviceInfoWindows().windowsInfo()` to bypass the issue temporary.

**Comment by sgsm74** [comment]
> Any fix available? wondering the reason why windows plugin not performed correctly.
> 
> I have to import `device_info_plus_windows` manually and directly call `device_info_windows.DeviceInfoWindows().windowsInfo()` to bypass the issue temporary.

Not yet :( , just waiting for any response...
