### ISSUE TITLE
Repeating alarm won't start when closing app, it get an issue

### ISSUE THREAD

**Issue by EnricoTirri** [fluttercommunity/plus_plugins#715]
java.lang.RuntimeException: Unable to create service dev.fluttercommunity.plus.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3577)
	at android.app.ActivityThread.access$1400(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
	at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:390)
	at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:104)
	at dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:155)
	at dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:124)
	at dev.fluttercommunity.plus.androidalarmmanager.AlarmService.onCreate(AlarmService.java:351)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3565)

**Comment by vbuberen** [comment]
Please report issue following our PR template.
Also, please search through issues first. I believe this is already reported.

**Comment by EnricoTirri** [comment]
where can I get this template?

**Comment by vbuberen** [comment]
When you click `New issue` and select `Found a bug` the body is already pre-filled. You just need to input your information. 

But, even with the info you already shared I feel like this is the same as https://github.com/fluttercommunity/plus_plugins/issues/649 which was already reported multiple times. If not, don't hesitate updating this issue with all the info from the template as I initially requested.

**Comment by EnricoTirri** [comment]
ok, it looks like that report, but it seems like it's been closed, so have you an idea why i continue having the same problem?
in the report issue, the person who opened it says that a hot-fix could be change the application name in the android manifest, but if I change it the app won't build because your package requires v2 embedding

**Comment by vbuberen** [comment]
The issue was closed because I merge a PR from one of maintainers ~1 hour ago. But new version still not released on pub.dev. So, please, wait till `2.0.4` is released and share the feedback afterwards.

**Comment by EnricoTirri** [comment]
thanks you a lot

**Comment by giorgionegro** [comment]
Roughly when we will have the new version?

**Comment by vbuberen** [comment]
It is already available

**Comment by giorgionegro** [comment]
Seams to work as intended to me

-------- Original Message --------
