### ISSUE TITLE
[package_info_plus] Does not work on Linux, Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

### ISSUE THREAD

**Issue by richardjharris** [fluttercommunity/plus_plugins#773]
## System info

Platform the Issue occurs on: Linux
Plugin name: package_info_plus
Plugin version: 1.4.0

## Steps to Reproduce

1. I added `await PackageInfo.fromPlatform()` to a function called from a `Drawer`, to get the version and call `showAboutDialog`
2. When the Drawer calls the function, no about dialog appears.
3. Debug console shows the following

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:377:43)
<asynchronous suspension>
#2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
<asynchronous suspension>
#3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:36:26)
<asynchronous suspension>
#4      NavigationDrawer.build.<anonymous closure> (package:yomikun/navigation/navigation_drawer.dart:89:41)
<asynchronous suspension>
```
Flutter doctor:

```
[✓] Flutter (Channel beta, 2.11.0-0.1.pre, on Manjaro Linux 5.16.11-2-MANJARO, locale en_GB.utf8)
    • Flutter version 2.11.0-0.1.pre at /home/rjh/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b101bfe32f (3 weeks ago), 2022-02-16 07:36:54 -0800
    • Engine revision e355993572
    • Dart version 2.17.0 (build 2.17.0-69.2.beta)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 5.16.11-2-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51 unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

I already tried running `flutter clean` and restarting, so I am not sure what to do.

**Comment by richardjharris** [comment]
The contents of `linux/flutter/generated_plugin_registrant.cc`:

```
#include "generated_plugin_registrant.h"

#include <url_launcher_linux/url_launcher_plugin.h>

void fl_register_plugins(FlPluginRegistry* registry) {
  g_autoptr(FlPluginRegistrar) url_launcher_linux_registrar =
      fl_plugin_registry_get_registrar_for_plugin(registry, "UrlLauncherPlugin");
  url_launcher_plugin_register_with_registrar(url_launcher_linux_registrar);
}
```

**Comment by Chuanbin-Wang** [comment]
same problem.

**Comment by sgehrman** [comment]
same problem

**Comment by igorgoncalves** [comment]
same problem

**Comment by keanallen** [comment]
I've also got this issue on Windows Desktop. One of my packages use this package as its dependencies, and now im stuck :( Can you please prioritize this one?

**Comment by ctrysbita** [comment]
This should be fixed in #574
@vbuberen I think we should release a newer version of `package_info_plus_windows` and `package_info_plus_linux`.
A temporary workaround is adding override to your `pubspec.yaml` to use main branch.
```yaml
dependency_overrides:
  package_info_plus_windows:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      ref: main
      path: packages/package_info_plus/package_info_plus_windows
  package_info_plus_linux:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      ref: main
      path: packages/package_info_plus/package_info_plus_linux
```

**Comment by CoderWeiLee** [comment]
same problem

**Comment by fabiancrx** [comment]
@mhadaily  as [this comment](https://github.com/fluttercommunity/plus_plugins/issues/773#issuecomment-1073018063) the code in the repository already works for linux and windows, it would only be needed to update the versions and changelog in the `package_info_plus_*` and `package_info_plus` and update it at pub.dev so that users don't have to use the workarounds of using a lesser version or overriding the dependency with the latest on main. Should I make a PR with this changes?

**Comment by mhadaily** [comment]
@fabiancrx PR is always welcome, please do and properly mention that.
