### ISSUE TITLE
[Add-to-app: device_info_plus] ios app startup error, after integrating flutter module

### ISSUE THREAD

**Issue by see** [fluttercommunity/plus_plugins#785]
ios app startup error, after integrating flutter module

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getIosDeviceInfo on channel dev.fluttercommunity.plus/device_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MethodChannelDeviceInfo.iosInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:28:8)
<asynchronous suspension>
#2      DeviceInfoPlugin.iosInfo (package:device_info_plus/device_info_plus.dart:52:32)
<asynchronous suspension>
#3      DeviceInfo.getHeaderString (package:flutter_module/common/utils/device_info.dart:13:28)
<asynchronous suspension>
#4      HeaderInterceptors.onRequest (package:flutter_module/common/http_new/interceptors/header_interceptor.dart:13:33)
<asynchronous suspension>

```

**Comment by basemkhirat** [comment]
Same for me, any updates?

**Comment by lsfern** [comment]
同样的问题。看来只能手动注册了。

**Comment by Zeelsarvadhi** [comment]
Same for me, how to fix this error.?
