### ISSUE TITLE
[sensors_plus] Issue when running on Dart Isolate

### ISSUE THREAD

**Issue by gfran93** [fluttercommunity/plus_plugins#853]
Hi there! I found an issue trying to listen a sensor event from an Isolate.

Regards

## System info

Platform the Issue occurs on: Android 12
Plugin name: sensors_plus
Plugin version: 1.3.1

## Steps to Reproduce

1. Create a top level function which listens to a sensor event:

```Dart
void isolateTask(int n) {
  accelerometerEvents.listen(print);
}
```
2. On the initState method of your widget, compute the isolate:

```Dart
@override
  void initState() {
    super.initState();
    compute(isolateTask, 0);
  }
```

After this you will have the exception.

<details>
<summary>Logs</summary>

```dart
[  +10 ms] E/flutter (32644): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Null check operator used on a null value
[        ] E/flutter (32644): #0      EventChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:483:86)
[        ] E/flutter (32644): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:7)
[        ] E/flutter (32644): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:502:64)
[        ] E/flutter (32644): #3      _runGuarded (dart:async/stream_controller.dart:814:24)
[        ] E/flutter (32644): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
[        ] E/flutter (32644): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
[        ] E/flutter (32644): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
[        ] E/flutter (32644): #7      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
[        ] E/flutter (32644): #8      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
[        ] E/flutter (32644): #9      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
[        ] E/flutter (32644): #10     isolateTask (package:tracker_poc/screens/sensors_page.dart:87:23)
[        ] E/flutter (32644): #11     _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:83:34)
[        ] E/flutter (32644): #12     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:65)
[        ] E/flutter (32644): #13     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:89:5)
[        ] E/flutter (32644): #14     Timeline.timeSync (dart:developer/timeline.dart:163:22)
[        ] E/flutter (32644): #15     _spawn (package:flutter/src/foundation/_isolates_io.dart:87:35)
[        ] E/flutter (32644): #16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
[        ] E/flutter (32644): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[        ] E/flutter (32644): 

```

</details>

<details>
<summary>Flutter doctor output</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale es_UY.UTF-8)
    • Flutter version 2.10.5 at /home/gustavo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (hace 2 semanas), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/gustavo/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/gustavo/android-studio-2021.1.1.5
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/gustavo/android-studio-beta
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /snap/intellij-idea-community/357
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • SM S906E (mobile) • RFCT20P6JHA • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by ChristosMagiras** [comment]
Hi, I have the same issue...

**Comment by athenawisdoms** [comment]
Did you manage to solve the problem?
@gfran93 @ChristosMagiras

**Comment by Ortes** [comment]
Same here but with this error
`Unsupported operation: Background isolates do not support setMessageHandler(). Messages from the host platform always go to the root isolate.`
