### ISSUE TITLE
[Share_plus] I getting error when i try to share multiple images (around 6 to 7)

### ISSUE THREAD

**Issue by vatsa1101** [fluttercommunity/plus_plugins#866]
## System info

Platform the Issue occurs on: Android
Plugin name: Share_plus
Plugin version: 4.0.4

## Steps to Reproduce

I am trying to share multiple images (around 6 to 7) and its giving this error

<details>
<summary>Logs</summary>

[+12221 ms] W/Bundle  (11752): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value
was a java.lang.String.  The default value <null> was returned.
[   +2 ms] W/Bundle  (11752): Attempt to cast generated internal exception:
[        ] W/Bundle  (11752): java.lang.ClassCastException: java.lang.String cannot be cast to
java.util.ArrayList
[        ] W/Bundle  (11752):   at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1343)  
[        ] W/Bundle  (11752):   at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1145)
[        ] W/Bundle  (11752):   at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:8364)
[        ] W/Bundle  (11752):   at android.content.Intent.migrateExtraStreamToClipData(Intent.java:11345)
[        ] W/Bundle  (11752):   at android.content.Intent.migrateExtraStreamToClipData(Intent.java:11308)
[        ] W/Bundle  (11752):   at
android.app.Instrumentation.execStartActivity(Instrumentation.java:1721)
[        ] W/Bundle  (11752):   at android.app.Activity.startActivityForResult(Activity.java:5320)       
[        ] W/Bundle  (11752):   at android.app.Activity.startActivityForResult(Activity.java:5278)       
[        ] W/Bundle  (11752):   at android.app.Activity.startActivity(Activity.java:5664)
[        ] W/Bundle  (11752):   at android.app.Activity.startActivity(Activity.java:5617)
[        ] W/Bundle  (11752):   at dev.fluttercommunity.plus.share.Share.startActivity(Share.kt:160)     
[        ] W/Bundle  (11752):   at dev.fluttercommunity.plus.share.Share.shareFiles(Share.kt:152)        
[        ] W/Bundle  (11752):   at
dev.fluttercommunity.plus.share.MethodCallHandler.onMethodCall(MethodCallHandler.kt:46)
[        ] W/Bundle  (11752):   at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)       
[        ] W/Bundle  (11752):   at
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
[        ] W/Bundle  (11752):   at
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenge
r.java:320)
[        ] W/Bundle  (11752):   at
io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] W/Bundle  (11752):   at android.os.Handler.handleCallback(Handler.java:938)
[        ] W/Bundle  (11752):   at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] W/Bundle  (11752):   at android.os.Looper.loop(Looper.java:223)
[        ] W/Bundle  (11752):   at android.app.ActivityThread.main(ActivityThread.java:7656)
[        ] W/Bundle  (11752):   at java.lang.reflect.Method.invoke(Native Method)
[        ] W/Bundle  (11752):   at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[        ] W/Bundle  (11752):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

</details>

<details>
<summary>Flutter doctor output</summary>

```
```

</details>

**Comment by Shilpa26v** [comment]
@vatsa1101 
is image sharing working in ios ?

**Comment by sivaprasadnk** [comment]
This error also occurred to me , when more than 1 pdfs are shared.
