### ISSUE TITLE
Error: UnimplementedError: shareFiles() has not been implemented on Web.

### ISSUE THREAD

**Issue by vishalvishvakarma1111** [fluttercommunity/plus_plugins#909]
### Platform

Chrome web

### Plugin

share_plus

### Version

4.0.8

### Flutter SDK

2.10.5

### Steps to reproduce

just hit the function on while running on web 

Share.shareFiles([filePath]);

### Code Sample

```dart
String path="path";
Share.shareFiles([path]);
```

### Logs

```shell
Exception
Error: UnimplementedError: shareFiles() has not been implemented on Web.
    at Object.throw_ [as throw] (http://localhost:50447/dart_sdk.js:5391:11)
    at share_plus_web.SharePlusPlugin.new.shareFiles (http://localhost:50447/packages/share_plus_web/share_plus_web.dart.lib.js:78:17)
    at Share.shareFiles (http://localhost:50447/packages/share_plus/share_plus.dart.lib.js:45:41)
    at booking_options_popup_menu_widget.BookingOptionsPopupMenuWidget.new.<anonymous> (http://localhost:50447/packages/beauty_salons_owner/app/modules/account/controllers/account_controller.dart.lib.js:5748:36)
    at Generator.next (<anonymous>)
```

### Flutter Doctor

```shell
mac@macs-Mac-mini-4 zylu_business % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
mac@macs-Mac-mini-4 zylu_business %
```

**Comment by miquelbeltran** [comment]
That's just how it works, web doesn't support sharing files, only text. You will have to find a different solution for what you are trying to achieve.

**Comment by vishalvishvakarma1111** [comment]
ok
